"use strict";
// Vertiefung und Fortsetzung. Läuft vor der Präsentationssteuerung.
const sources = {
  ascii: "ASCII-Zeichentabelle: https://www.rfc-editor.org/rfc/rfc20.html",
  intel:
    "Intel, Instruction Set Reference: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
  arm: "Arm, A64 Instruction Set: https://developer.arm.com/documentation/ddi0602/latest/",
  python:
    "Python-Tutorial: https://docs.python.org/3/tutorial/introduction.html",
};
const book = (name, rows, color = "orange") =>
  `<div class="rulebook ${color}"><div class="book-title">${name}</div><div class="book-pages">${rows.map(([a, b]) => `<div class="book-row"><code>${a}</code><span>${b}</span></div>`).join("")}</div><div class="book-spine"></div></div>`;
const scene = (name, alt) =>
  `<img class="scene" src="assets/${name}.svg" alt="${alt}">`;
const codeCard = (title, code, cls = "") =>
  `<div class="code-card ${cls}"><div class="code-title">${title}</div><pre>${code}</pre></div>`;
const S = (chapter, title, html, bottom, notes, extra = {}) => ({
  chapter,
  title,
  eyebrow: chapter,
  heading: title,
  html,
  bottom,
  notes,
  ...extra,
});
const codeWord = (op, val) =>
  `<span class="orange">${op}</span><span class="soft"> | </span><span class="blue">${val}</span>`;
const modelProgram = `<div class="program-list"><div class="program-row"><span class="line-no">0</span><code>${codeWord("0001", "00000101")}</code><span>5 übernehmen</span></div><div class="program-row"><span class="line-no">1</span><code>${codeWord("0010", "00000011")}</code><span>3 dazuzählen</span></div><div class="program-row"><span class="line-no">2</span><code>${codeWord("0011", "00000000")}</code><span>Ergebnis bei Datenplatz 0 ablegen</span></div></div>`;

const conventions = [
  S(
    "Bedeutung vereinbaren",
    "Was bedeutet 01000001?",
    `<div class="context-bit">01000001</div><div class="grid three">${frag(1, '<small>Als vorzeichenlose Zahl</small><strong class="big blue">65</strong><p>64 + 1</p>', "card")}${frag(2, '<small>Als ASCII-Zeichen</small><strong class="big orange">A</strong><p>Eine vereinbarte Zuordnung</p>', "card")}${frag(3, '<small>Als Bildzeile</small><div class="pixel-strip">' + [0, 1, 0, 0, 0, 0, 0, 1].map((x) => `<span class="pixel p${x}"></span>`).join("") + "</div><p>Hier: 0 = dunkel, 1 = hell</p>", "card")}</div>`,
    "Dieselben Bits. Unterschiedliche Regeln. Unterschiedliche Bedeutung.",
    note(
      "Die Bedeutung einer Bitfolge ausdrücklich als Konvention erklären.",
      "Steckt in diesen Bits zwingend die Zahl 65?",
      "Als Zahl ja; sie könnten auch einen Buchstaben darstellen.",
      "Zuerst 64 + 1 herleiten. Dann ASCII als vereinbarte Zeichentabelle einführen: Code 65 steht dort für A. ASCII hat sieben Bits; hier ist es mit führender 0 in acht Bits dargestellt. Schließlich dieselben acht Bits als acht Pixel einer selbst vereinbarten Bildzeile lesen. Ein Pixel ist ein einzelner Bildpunkt. Diese Bildregel ist kein behauptetes Dateiformat.",
      "Die Bits enthalten nicht gleichzeitig alle drei Bedeutungen für denselben Verarbeitungsschritt. Die Anwendung verwendet eine bestimmte Deutungsregel.",
      "Wie machen wir sichtbar, welche Regel wir gerade benutzen?",
      "1: Zahl. 2: Buchstabe. 3: Pixelmuster.",
      sources.ascii,
    ),
  ),
  S(
    "Bitfolge + Wörterbuch",
    "Das „Wörterbuch“ macht den Unterschied",
    `<div class="dictionary-equation"><div class="card"><small>Bitfolge</small><code class="big-bits">01000001</code></div><span class="math-sign">+</span>${book(
      "Vereinbarte Regeln",
      [
        ["01000000", "@"],
        ["01000001", "A"],
        ["01000010", "B"],
      ],
    )}<span class="math-sign">=</span><div class="meaning-result orange">A</div></div>${frag(1, '<div class="answer">Bitfolge + passende Deutungsregeln → Bedeutung<small>Der Kontext bestimmt, welche Regeln wir anwenden.</small></div>')}`,
    "Das Wörterbuch ist eine Metapher für eine feste Zuordnung.",
    note(
      "Das zentrale mentale Bild für alle folgenden Ebenen etablieren.",
      "Was müssen Sender und Empfänger zusätzlich zu den Bits gemeinsam kennen?",
      "Die Tabelle, die Sprache oder das Format.",
      "Die Bits allein reichen nicht. Beide Seiten müssen wissen, wie sie gruppiert und interpretiert werden. Kontext heißt hier zum Beispiel: Dieser Bereich wird als ASCII-Text verarbeitet. Ein Wörterbuch ist ein anschauliches Bild für die Zuordnung, nicht zwingend eine echte Datei.",
      "Auch die Gruppierung zählt. Nicht jede beliebige Bitfolge ist in jedem Format gültig. Ein Prozessor oder Programm darf Regeln nicht mitten im Ablauf willkürlich erraten.",
      "Kann derselbe Text in verschiedenen Zeichencodierungen andere Bits erhalten?",
      "1: Merksatz nach der gemeinsamen Betrachtung.",
      sources.ascii,
    ),
  ),
  S(
    "Eine Konvention ist eine Vereinbarung",
    "Könnten wir A anders codieren?",
    `<div class="grid two">${book("ASCII · tatsächlich verwendet", [
      ["01000001", "A"],
      ["01000010", "B"],
      ["01000011", "C"],
    ])}${book(
      "Geheimschrift · frei erfunden",
      [
        ["00000001", "A"],
        ["00000010", "B"],
        ["00000011", "C"],
      ],
      "blue",
    )}</div>${answer(1, "Ja – wenn beide Seiten dieselbe Vereinbarung verwenden.", "Die ASCII-Tabelle lässt sich dadurch nicht nachträglich ändern. Unsere neue Tabelle wäre eine andere Codierung.")}`,
    "Standards schaffen gemeinsame Regeln, auf die sich andere verlassen können.",
    note(
      "Konvention nicht mit beliebiger Auslegung eines vorhandenen Standards verwechseln.",
      "Dürften wir für unser eigenes System A mit 00000001 codieren?",
      "Ja, aber der Empfänger muss die Geheimschrift kennen.",
      "Links ein Ausschnitt der echten ASCII-Tabelle. Rechts ein neu erfundenes Alphabet. Beide können funktionieren, wenn die verarbeitenden Systeme darauf ausgelegt sind. ASCII selbst ist eine feste Spezifikation und nicht durch unsere eigene Vorliebe veränderbar.",
      "Konvention bedeutet nicht, dass vorhandene Hardware oder Software jede neue Zuordnung automatisch versteht.",
      "Was passiert, wenn die falsche Tabelle benutzt wird?",
      "1: Antwort auflösen.",
      sources.ascii,
    ),
  ),
  S(
    "Denkpause · Das falsche Wörterbuch",
    "Eine Datei enthält 01000001",
    `<div class="choices"><button class="choice" data-choice><b>A</b>Dann muss in jedem Programm ein A erscheinen.</button><button class="choice" data-choice><b>B</b>Wir müssen wissen, wie das Programm diese Bits interpretiert.</button></div>${answer(1, "B · Erst Format und Kontext legen die Bedeutung fest.", "Als Zahl: 65. Als ASCII-Text: A. Im vereinbarten Pixelmodell: eine Bildzeile.")}`,
    "Auch Maschinenanweisungen brauchen solche festgelegten Regeln.",
    note(
      "Das Wörterbuchmodell auf unbekannte Daten übertragen.",
      "Warum kann dasselbe gespeicherte Muster unterschiedlich dargestellt werden?",
      "Weil Programme verschiedene Datenformate erwarten.",
      "Eine Datei ist nicht automatisch Text. Ihre Bytes können Bilddaten, Zahlen oder Anweisungen darstellen. Auch Dateiendung und Dateiinhalte können Hinweise auf das Format liefern; nicht vertiefen.",
      "Man kann die Bedeutung nicht allein am hier isolierten Muster ablesen.",
      "Bevor wir CPU-Anweisungen codieren, klären wir, wo die CPU Werte bereithält und ablegt.",
      "Auswählen, begründen, dann 1: Auflösung.",
    ),
  ),
];

const architectures = [
  S(
    "Optionaler Exkurs · nur bei Interesse",
    "Warum sieht Assembly anderswo anders aus?",
    `<div class="grid two"><div class="card"><span class="term orange">Andere CPU-Architektur</span><h3>Andere Maschinenregeln</h3><p>Andere Register, Befehlsformate und Bitfolgen.</p><code>MOV EAX, 5 ↔ MOV W0, #5</code></div><div class="card"><span class="term blue">Andere Assembly-Syntax</span><h3>Andere Schreibkonvention</h3><p>Dieselbe CPU und dieselben Bits können anders notiert werden.</p><code>MOV EAX, 5 ↔ movl $5, %eax</code></div></div>`,
    "Zusatzfolien: Der Hauptteil ist abgeschlossen.",
    note(
      "Architektur und Schreibkonvention als zwei Gründe für unterschiedliche Darstellungen unterscheiden.",
      "Bedeutet eine andere Schreibweise immer eine andere CPU?",
      "Nein; auch für dieselbe CPU gibt es unterschiedliche Assembly-Syntax.",
      "Die nächsten Folien sind nur bei Fragen nötig. Unterschiedliche Architekturen haben unterschiedliche Maschinenregeln. Unterschiedliche Syntax kann dagegen nur die menschliche Notation derselben Maschinenanweisung verändern. Unser frühes Format mit vier Opcode- und acht Operandenbits ist ein bewusst kleines didaktisches Format. Die später gezeigten MOV/ADD-Bytes sind reales x86-64. Es gibt keine universelle Codetabelle für alle CPUs.",
      "Nicht einen Syntaxwechsel mit dem Wechsel der Hardwarearchitektur gleichsetzen.",
      "Zunächst zwei reale Architekturbeispiele vergleichen.",
      "Keine Einblendung; den Exkurs nur bei Interesse beginnen.",
      "",
    ),
  ),
  S(
    "Exkurs · Reale CPU-Architekturen",
    "Auch CPUs haben unterschiedliche Regeln",
    `<div class="grid two"><div class="architecture-card">${icon("cpu")}<h3>x86-64</h3><p>Zum Beispiel Prozessoren von Intel und AMD</p>${book(
      "x86-64-Befehlssatz",
      [
        ["…", "Wert übernehmen"],
        ["…", "addieren"],
      ],
    )}</div><div class="architecture-card arm">${icon("cpu")}<h3>AArch64 / ARM64</h3><p>Zum Beispiel Apple Silicon und viele Mobilprozessoren</p>${book(
      "A64-Befehlssatz",
      [
        ["…", "Wert übernehmen"],
        ["…", "addieren"],
      ],
      "blue",
    )}</div></div>${frag(1, '<p class="mini">Ein <em>Befehlssatz</em> legt fest, welche Maschinenanweisungen eine CPU ausführen kann und wie sie codiert sind.</p>')}`,
    "Ähnliche Aufgaben – aber unterschiedliche Anweisungen und Codierungen.",
    note(
      "Befehlssatz und reale Architekturbeispiele einführen.",
      "Müssen zwei verschiedene Prozessorarten dieselben Bits für dieselbe Aufgabe verwenden?",
      "Nein, sie können unterschiedliche Regeln haben.",
      "x86-64 und AArch64 sind reale Befehlssatzarchitekturen. A64 bezeichnet den hier verwendeten Arm-Befehlssatz. Architektur umfasst mehr als nur ein Wörterbuch, etwa sichtbare Register und weitere Regeln. Die dargestellten Geräte sind Beispiele, keine exklusive Zuordnung: Auch Server können Arm verwenden.",
      "Ein Prozessor lädt nicht einfach das Wörterbuch einer anderen Architektur und kann dann deren Code direkt ausführen. Emulation oder Übersetzung wäre ein zusätzlicher Mechanismus.",
      "Wir vergleichen jetzt zwei wirklich assemblierte Maschinenanweisungen.",
      "1: Den Namen Befehlssatz einführen.",
      sources.intel + "; " + sources.arm,
    ),
  ),
  S(
    "Exkurs · Reale Codierungen",
    "Gleiche Aufgabe. Andere Bitfolge.",
    `<p class="task-banner">Aufgabe: <strong>Die Zahl 5 in einem 32-Bit-Rechenplatz bereitstellen.</strong></p><div class="grid two"><div class="architecture-card"><h3>x86-64</h3><div class="real-bytes">10111000 00000101<br>00000000 00000000 00000000</div><div class="code-caption">5 Gruppen mit je 8 Bits</div></div><div class="architecture-card arm"><h3>AArch64 / ARM64</h3><div class="real-bytes">10100000 00000000<br>10000000 01010010</div><div class="code-caption">4 Gruppen mit je 8 Bits</div></div></div>${answer(1, "Beide stellen den Wert 5 bereit. Die Codierung passt jeweils zur Architektur.", "Gezeigt sind vollständige Anweisungen: Operationscodierung und weitere Felder, nicht nur ein Opcode.")}`,
    "Gezeigt sind vollständige Anweisungen in Speicherreihenfolge.",
    note(
      "Unterschiedliche echte Codierungen visuell belegen.",
      "Würden die Bits der linken Anweisung unverändert zur rechten CPU passen?",
      "Nicht allgemein; jede Architektur hat eigene Regeln.",
      "Links MOV EAX,5 im x86-64-Modus: B8 05 00 00 00. Rechts MOV W0,#5, Alias für MOVZ W0,#5: A0 00 80 52 als Bytes im Speicher; das 32-Bit-Instruktionswort lautet 528000A0 hexadezimal. Jeweils 32-Bit-Rechenplatz wählen, damit das Beispiel vergleichbar ist. Ein Byte ist eine Gruppe von acht Bits. Little Endian benennt die Speicherreihenfolge; die Details stehen in examples/README.md und sind hier kein Lernziel. Beide Beispiele wurden mit Clang assembliert und mit objdump geprüft.",
      "Nicht die Länge einer einzelnen Anweisung als allgemeine Eigenschaft jedes Opcodes ausgeben. Der erste Byteblock ist nicht in beiden Architekturen allein der Opcode.",
      "Jetzt vergleichen wir die vollständige Rechnung in beiden Assembly-Schreibweisen.",
      "1: Gemeinsame Bedeutung zeigen. Registerbezeichnungen erst später vertiefen.",
      sources.intel + "; " + sources.arm,
    ),
  ),
  S(
    "Exkurs · dieselbe Rechnung, andere Register",
    "5 + 3 auf x86-64 und AArch64",
    `<div class="grid two"><div>${codeCard("x86-64 · Intel-Syntax", "MOV EAX, 5\nADD EAX, 3")}<p class="mini">EAX ist Ziel und bisheriger Summand.<br>Danach: EAX = 8.</p></div><div>${codeCard("AArch64 · A64-Syntax", "MOV W0, #5\nADD W0, W0, #3")}<p class="mini">Ziel und erster Summand sind einzeln genannt.<br>Danach: W0 = 8.</p></div></div>${frag(1, '<div class="answer">W0 und EAX sind hier 32-Bit-Register.<small>Das # in der rechten Schreibweise kennzeichnet einen direkt angegebenen Wert.</small></div>')}`,
    "Beide berechnen 8; weitere Wirkungen einzelner Befehle können verschieden sein.",
    note(
      "Gleiche Rechenabsicht mit konkreten Register- und Operandenunterschieden zeigen.",
      "Warum taucht W0 in der rechten Addition zweimal auf?",
      "Einmal als Ziel und einmal als Eingabewert.",
      "Bei ADD EAX,3 wird EAX gelesen und überschrieben. ADD W0,W0,#3 nennt Ziel und ersten Eingang separat. Dadurch kann beispielsweise ADD W1,W0,#3 das Ergebnis in W1 ablegen und W0 erhalten. Bei x86 lässt sich ein ähnlicher Effekt durch eine Kopie und Addition oder passende andere Befehle erreichen. W0 ist die 32-Bit-Sicht eines Arm-Registers. x86 ADD verändert Statusflags, A64 ADD ohne S nicht. MOV W0,#5 ist hier ein Alias für MOVZ.",
      "Gleicher Ergebniswert bedeutet nicht, dass jedes Nebenverhalten der beiden Anweisungen identisch ist.",
      "Auch bei identischer CPU können wir die Notation wechseln.",
      "1: Gemeinsam auflösen.",
      "Intel SDM: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html ; Arm A64: https://developer.arm.com/documentation/ddi0602/latest/",
    ),
  ),
  S(
    "Exkurs · zwei Schreibweisen für dieselbe CPU",
    "Intel-Syntax und AT&T-Syntax",
    `<div class="grid two"><div>${codeCard("Intel · Ziel zuerst", "MOV EAX, 5\nADD EAX, 3")}<p class="mini">Wenige Sonderzeichen.<br>Die Datengröße ergibt sich hier aus EAX.</p></div><div>${codeCard("AT&amp;T · Quelle zuerst", "movl $5, %eax\naddl $3, %eax")}<p class="mini">$ kennzeichnet Werte, % Register.<br>l kennzeichnet hier die 32-Bit-Operation.</p></div></div>${frag(1, '<div class="answer">Beide ergeben hier dieselben Maschinenbytes.<small>10111000 00000101 00000000 00000000 00000000<br>10000011 11000000 00000011</small></div>')}`,
    "Andere Notation verändert hier Lesbarkeit und Werkzeugbedienung, nicht die Ausführung.",
    note(
      "Syntax als menschliche Konvention vom Befehlssatz trennen.",
      "Wird das Programm durch mehr Sonderzeichen langsamer?",
      "Nein, wenn beide Schreibweisen dieselben Bytes ergeben.",
      "Intel schreibt für diese Befehle Ziel, Quelle; AT&T schreibt Quelle, Ziel. Die Präfixe $ und % sowie das Suffix l machen Wert, Register und Datengröße ausdrücklich sichtbar. Intel ist oft kompakter; bei bestimmten Speicheroperationen ist dort eine zusätzliche Größenangabe nötig. Welche Notation leichter zu lesen ist, hängt von Übung und Werkzeugen ab. Beide Beispiele wurden mit demselben Assembler zur gleichen Bytefolge übersetzt.",
      "Die Operandendrehung ist keine Rechenumkehr; beide setzen EAX auf 5 und addieren 3. Keine allgemeine Geschwindigkeitswertung aus der Syntax ableiten.",
      "Warum haben Architekturen selbst unterschiedliche Formate?",
      "1: Gemeinsam auflösen.",
      "GNU as, Intel und AT&T: https://sourceware.org/binutils/docs/as/i386_002dVariations.html",
    ),
  ),
  S(
    "Exkurs · warum unterschiedliche Entwürfe?",
    "Befehlsformate haben unterschiedliche Stärken",
    `<div class="grid two"><div class="architecture-card"><h3>x86-64 · variable Länge</h3><div class="byte-ruler"><span>1</span><span>2</span><span>3</span><span>…</span><span>15 Bytes</span></div><p>Kurze Codierungen sind möglich.<br>Die Befehlsgrenzen sind aufwendiger zu erkennen.</p><p>Historisch gewachsen: viel bestehende Software und zahlreiche Erweiterungen.</p></div><div class="architecture-card arm"><h3>A64 · immer 4 Bytes</h3><div class="byte-ruler"><span>1</span><span>2</span><span>3</span><span>4 Bytes</span></div><p>Regelmäßige Befehlsgrenzen.<br>Für große Werte sind manchmal mehrere Befehle nötig.</p><p>Eigenständiger Entwurf mit festen Feldern und vielen Registern.</p></div></div>${frag(1, '<p class="mini">Länge und Befehlssatz allein verraten nicht, welche CPU schneller oder sparsamer ist.</p>')}`,
    "Entwurfsziele, historische Kompatibilität und verfügbare Bitfelder prägen eine Architektur.",
    note(
      "Konkrete Vor- und Nachteile ohne pauschales Architekturranking erklären.",
      "Was gewinnt man, wenn jede Anweisung dieselbe Länge hat?",
      "Man erkennt die Grenzen regelmäßiger; im festen Platz sind nicht beliebig viele Informationen unterzubringen.",
      "x86-Instruktionen haben variable Länge bis 15 Bytes. A64-Instruktionen sind 32 Bits lang. Kurze x86-Codierungen können Platz sparen; die variable Struktur macht das Decodieren komplexer. Feste A64-Längen erleichtern das Bestimmen von Anweisungsgrenzen, begrenzen aber den Platz etwa für direkt codierte Konstanten. Auch x86 hat Grenzen und braucht für manche Werte mehrere Schritte. Diese Eigenschaften erlauben keine pauschale Aussage über Leistung, Codegröße oder Energieverbrauch eines ganzen Programms. Implementierung, Fertigung und Arbeitslast spielen mit.",
      "A64 nicht mit jedem Arm-Befehlssatz gleichsetzen: etwa Thumb hat andere Längenregeln. Ein einzelner kurzer Befehl beweist keine allgemeine Überlegenheit.",
      "Zur Abschlussrechnung zurückkehren oder mit dem nächsten Seminarabschnitt fortfahren.",
      "1: Gemeinsam auflösen.",
      "Intel SDM: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html ; Arm: https://developer.arm.com/community/arm-community-blogs/b/architectures-and-processors-blog/posts/the-a64-isa-and-compilers",
    ),
  ),
];

const construction = [
  S(
    "Von Hand konstruieren · 1 von 3",
    "Zuerst die 5 bereitstellen",
    `<div class="construction"><div>${book("Unser Befehlssatz", [
      ["0001", "Wert übernehmen"],
      ["0010", "addieren"],
      ["0011", "ablegen"],
    ])}</div><div class="build-steps">${frag(1, '<span class="label">1 · Operation nachschlagen</span><code class="orange">0001</code>')}${frag(2, '<span class="label">2 · Wert als Bits schreiben</span><code class="blue">5 = 00000101</code>')}${frag(3, '<span class="label">3 · Nach dem Format zusammensetzen</span><code>' + codeWord("0001", "00000101") + "</code>")}</div></div>${model}`,
    "Die erste Anweisung setzt den Rechenstand auf 5.",
    note(
      "Eine Maschinenanweisung aus Absicht, Befehlstabelle und Zahlenformat herleiten.",
      "Wie bauen wir die erste Anweisung, ohne bereits einen Rechenstand vorauszusetzen?",
      "Wert übernehmen wählen, 5 binär darstellen, Felder zusammensetzen.",
      "Wir verwenden das bekannte einfache 12-Bit-Befehlsformat. Vier Bits codieren die Operation, acht Bits den Wert beziehungsweise die Adresse. Für LOAD 5 ergibt das 0001 | 00000101. Der Trennstrich wird nur zur Lesbarkeit gedruckt und gehört nicht zum Maschinencode.",
      "Die Zahl 5 ist ein Operand und nicht der Opcode. Ein bestehender Rechenstand wird durch LOAD ersetzt.",
      "Jetzt fehlt das Dazuzählen der 3.",
      "1: Operation. 2: Wert. 3: Ganze Anweisung.",
    ),
  ),
  S(
    "Von Hand konstruieren · 2 von 3",
    "Dann die 3 dazuzählen",
    `<div class="construction"><div>${book("Unser Befehlssatz", [
      ["0001", "Wert übernehmen"],
      ["0010", "addieren"],
      ["0011", "ablegen"],
    ])}</div><div class="build-steps">${frag(1, '<span class="label">1 · Operation nachschlagen</span><code class="orange">0010</code>')}${frag(2, '<span class="label">2 · Wert als Bits schreiben</span><code class="blue">3 = 00000011</code>')}${frag(3, '<span class="label">3 · Zweite Anweisung</span><code>' + codeWord("0010", "00000011") + "</code>")}</div></div>${model}`,
    "Der bisherige Rechenstand 5 wird durch die Addition zu 8.",
    note(
      "Das Konstruktionsverfahren an der zweiten Anweisung anwenden.",
      "Welchen Opcode und welchen Wert brauchen wir jetzt?",
      "0010 für ADD und 00000011 für 3.",
      "Die Anweisung addiert zum Rechenstand, den die erste Anweisung bereitgestellt hat. Die erste Anweisung muss davor ausgeführt werden. 3 besteht aus 2 + 1.",
      "Ein zweites LOAD 3 würde die 5 überschreiben und nicht addieren.",
      "Wollen wir das Ergebnis außerhalb dieses Rechenplatzes sichern?",
      "1–3: Schrittweise selbst herleiten lassen.",
    ),
  ),
  S(
    "Von Hand konstruieren · 3 von 3",
    "Das Ergebnis an einem Platz ablegen",
    `<div class="grid two"><div>${book("Unser Befehlssatz", [["0011", "Ergebnis ablegen"]])}<p class="mini">Wir wählen den nummerierten Datenplatz 0.</p></div><div class="memory-drawer"><span>Datenplatz 0</span><strong class="fragment" data-step="2">8</strong></div></div>${frag(1, '<div class="assembled-line"><code>' + codeWord("0011", "00000000") + '</code><p>Ablegen <span class="soft">|</span> Adresse 0</p></div>')}${model}`,
    "Hier bezeichnet das blaue Feld einen Speicherplatz, nicht den Zahlenwert des Ergebnisses.",
    note(
      "Einen Adressoperanden am greifbaren Ablageplatz erklären.",
      "Müssen wir der STORE-Anweisung die 8 oder den Ablageplatz mitgeben?",
      "Den Ablageplatz. Der Rechenstand enthält das Ergebnis bereits.",
      "Eine Adresse ist hier die Nummer eines Speicherplatzes. STORE 0 bedeutet: Lege den aktuellen Rechenstand an Datenadresse 0 ab. 00000000 codiert diese Adresse. In unserem Beispiel sind Daten- und Anweisungsspeicher getrennt. Zum eigentlichen Rechnen reichen LOAD und ADD; STORE ist der zusätzliche Schritt zum Sichern des Ergebnisses.",
      "STORE 0 speichert nicht die Zahl 0. Die Rolle des Operandenfelds hängt von der Operation ab.",
      "Drei selbst konstruierte Maschinenanweisungen bilden nun unseren kleinen Programmausschnitt.",
      "1: Ganze Anweisung. 2: Der Platz erhält 8.",
    ),
  ),
  S(
    "Unser erstes Maschinenprogramm",
    "Drei Anweisungen für 5 + 3",
    `${model}${modelProgram}${frag(1, '<p class="mini">Zuerst 5 übernehmen → dann 3 addieren → Ergebnis an Datenplatz 0 ablegen.</p>')}`,
    "Die Reihenfolge gehört zum Programm. Drei Opcodes allein würden nicht reichen.",
    note(
      "Die vollständige Folge mit Operanden zeigen und von bloßen Opcodes abgrenzen.",
      "Was ginge verloren, wenn wir nur 0001, 0010 und 0011 aufschreiben?",
      "Die Werte 5 und 3 und die Speicheradresse 0.",
      "Links stehen die Anweisungsadressen 0, 1, 2, also ihre Positionen im separaten Anweisungsspeicher. Jede Zeile enthält vier Operationsbits und acht Wert- oder Adressbits. Das ist ein Programmausschnitt; ein echter Start-/Stoppmechanismus wird hier nicht modelliert.",
      "Das Programm besteht aus vollständigen Maschinenanweisungen, nicht nur aus Operationscodes. Adresse 0 im Datenbereich ist unabhängig von Anweisungsadresse 0.",
      "Wie verarbeitet die CPU eine solche Liste Schritt für Schritt?",
      "1: Gesamtablauf in Worten lesen lassen.",
    ),
  ),
  S(
    "Holen → Decodieren → Ausführen",
    "Eine Anweisung nach der anderen",
    `<div class="cycle"><div class="cycle-step"><span class="cycle-number">1</span><h3>Holen</h3><p>Die nächste Anweisung aus dem Speicher holen.</p><small>FETCH</small></div><span class="arrow">→</span>${frag(1, '<span class="cycle-number">2</span><h3>Decodieren</h3><p>Die Bitfelder nach dem Befehlssatz auswerten.</p><small>DECODE</small>', "cycle-step")}<span class="arrow fragment" data-step="2">→</span>${frag(2, '<span class="cycle-number">3</span><h3>Ausführen</h3><p>Die festgelegte Operation durchführen.</p><small>EXECUTE</small>', "cycle-step")}</div>${frag(3, '<div class="cycle-return">↶ Danach die nächste Anweisung holen.</div>')}`,
    "Decodieren heißt Regeln anwenden – nicht wie ein Mensch über die Absicht nachdenken.",
    note(
      "Fetch–Decode–Execute als wiederkehrenden Grundablauf erklären.",
      "Was muss passieren, bevor eine Anweisung ausgeführt werden kann?",
      "Sie muss geholt und erkannt werden.",
      "Holen stellt die Bits bereit. Decodieren wertet Felder nach den Regeln des Befehlssatzes aus. Ausführen verändert den Zustand. Reale CPUs können Phasen überlappen oder intern weitere Schritte verwenden; diese logische Sicht eignet sich für das Verständnis.",
      "Das Modell bedeutet nicht, dass moderne CPUs immer streng eine komplette Anweisung nach der anderen ohne Überlappung bearbeiten.",
      "Wir verbinden den Ablauf jetzt mit dem bekannten Register und dem RAM.",
      "1: Decode. 2: Execute. 3: Rückweg.",
    ),
  ),
  S(
    "Wir spielen CPU · Schritt für Schritt",
    "Unser Programm in Bewegung",
    `<div class="cpu-demo"><div class="sim-program">${modelProgram}</div><div class="sim-machine"><div class="phase-track"><span data-phase="1">Holen</span><span data-phase="2">Decodieren</span><span data-phase="3">Ausführen</span></div><div class="instruction-slot"><small>Geholte Anweisung</small><code data-sim-word>–</code><p data-sim-meaning>Noch keine Anweisung geholt.</p></div><div class="sim-storage"><div><small>CPU-Register</small><strong data-cpu-register>?</strong></div><div><small>RAM · Datenplatz 0</small><strong data-cpu-memory>?</strong></div></div></div></div>${Array.from({ length: 9 }, (_, i) => `<span class="sr-only fragment" data-step="${i + 1}">Schritt ${i + 1}</span>`).join("")}${model}`,
    "Mit jedem Klick genau eine Phase. Rückwärts blättern stellt den vorigen Zustand wieder her.",
    note(
      "Opcodefolge und Fetch–Decode–Execute in einer überprüfbaren Zustandsdarstellung zusammenführen.",
      "Wann ändert sich das Register: beim Holen, beim Decodieren oder erst beim Ausführen?",
      "Erst beim Ausführen.",
      "Eine Person liest die Anweisung aus dem RAM vor, eine wendet den Befehlssatz an, eine aktualisiert das Register. Nach LOAD steht 5 im Register. Nach ADD steht 8 darin. STORE schreibt 8 an Datenplatz 0 und lässt das Register auf 8. Das ist eine geführte Simulation des angegebenen Ausschnitts, keine allgemeine CPU-Emulation. Nach neun Schritten hält die Darstellung an, nicht automatisch jede reale CPU.",
      "Geholte Bits und berechneter Wert sind verschiedene Dinge. Die CPU sieht nicht die daneben stehenden deutschen Erläuterungen.",
      "Jetzt können wir einen fehlerhaft geordneten Ablauf erkennen.",
      "1–3: LOAD holen/decodieren/ausführen. 4–6: ADD. 7–9: STORE.",
    ),
    { demo: "cpu" },
  ),
  S(
    "Denkpause · Fehler im Ablauf",
    "Was liegt am Ende im Register?",
    `${model}<div class="program-list"><div class="program-row"><span class="line-no">0</span><code>${codeWord("0001", "00000101")}</code><span>5 übernehmen</span></div><div class="program-row"><span class="line-no">1</span><code>${codeWord("0001", "00000011")}</code><span>3 übernehmen</span></div></div>${answer(1, "3 · Die zweite Anweisung ersetzt die 5.", "Für 5 + 3 müsste der zweite Opcode 0010 sein: addieren.")}`,
    "Gleiche Werte allein garantieren noch nicht dieselbe Rechnung.",
    note(
      "Die Bedeutung des Opcodes und die Zustandsänderung prüfen.",
      "Ergibt dieser Ablauf 8 oder 3 – und warum?",
      "3, weil beide Anweisungen LOAD verwenden.",
      "In dieser Variante ist nur der zweite Opcode gegenüber dem richtigen Ablauf verändert. LOAD setzt den Rechenstand; es addiert nicht. Wer 8 vermutet, soll jede Zeile nacheinander mit dem Register durchspielen.",
      "Nicht allein aus den Zahlen 5 und 3 auf Addition schließen. Die Operation ist wesentlich.",
      "Das von Hand zu schreiben ist machbar, aber für Menschen mühsam.",
      "1: Ergebnis und nötige Korrektur.",
    ),
  ),
];

const continuation = [
  S(
    "Assembly · lesbare Maschinenbefehle",
    "Würdet ihr lieber Wörter lesen?",
    `<div class="grid two">${codeCard("Maschinencode · Bits im Speicher", "10111000 00000101 00000000\n00000000 00000000\n10000011 11000000 00000011", "compact-code")}${codeCard("Dieselbe Folge · Assembly", '<span class="orange">MOV</span> EAX, <span class="blue">5</span>\n<span class="orange">ADD</span> EAX, <span class="blue">3</span>')}</div><p class="mini"><span class="mint">EAX</span> ist unser 32-Bit-Register. Das E steht für <em>Extended</em>: die erweiterte Form des historischen Akkumulatorregisters AX.</p>${frag(1, '<div class="answer">Assembly gibt Maschinenoperationen menschenlesbare Namen.<small>MOV und ADD sind Lesehilfen für Menschen. Die CPU führt weiterhin die codierten Anweisungen aus.</small></div>')}`,
    "Wörter und Bits stellen hier dieselben zwei vollständigen Anweisungen dar.",
    note(
      "Assembly als Antwort auf mühsame Bitfolgen einführen.",
      "Welche Seite lässt sich leichter lesen und korrigieren?",
      "Die Wörter rechts.",
      "Der linke Ausschnitt ist die tatsächlich assemblierte Folge MOV EAX,5; ADD EAX,3. EAX ist ein 32-Bit-Register der x86-Architektur. E steht für Extended, AX ist der historische Name des 16-Bit-Akkumulatorregisters. Akkumulator meint einen Rechenplatz, an dem sich Ergebnisse sammeln. Häufig wird EAX als Extended Accumulator bezeichnet. Es ist heute auch allgemein verwendbar. Die ersten fünf Bytegruppen gehören zu MOV, die nächsten drei zu ADD. Der Zeilenumbruch innerhalb der ersten Anweisung dient nur dem Platz. Keine funktionale Ausgabe oder vollständige ausführbare Datei behaupten.",
      "MOV heißt nicht, dass eine physische Zahl durch den Raum bewegt wird. Die CPU führt nicht die Zeichen M, O und V als diesen Opcode aus.",
      "Was bedeuten die drei Teile der lesbaren Anweisung?",
      "1: Begriff Assembly.",
      sources.intel,
    ),
  ),
  S(
    "Assembly lesen",
    "Was bedeutet MOV EAX, 5?",
    `<div class="assembly-parts"><div><code class="orange">MOV</code><span>Wert übertragen</span></div><div><code class="mint">EAX</code><span>Register als Ziel</span></div><div><code class="blue">5</code><span>angegebener Wert</span></div></div>${frag(1, '<div class="definition">Setze das Register <span class="mint">EAX</span> auf den Wert <span class="blue">5</span>.</div>')}`,
    "EAX: 32 Bits Platz für unseren aktuellen Rechenwert.",
    note(
      "Einzelne Teile ohne mehrere neue Begriffe gleichzeitig zerlegen.",
      "Welcher Teil bezeichnet die Operation, welcher den Rechenplatz, welcher den Wert?",
      "MOV, EAX und 5.",
      "MOV ist der menschenlesbare Befehlsname, auch Mnemonic genannt. Den zusätzlichen Fachbegriff nur bei Interesse erwähnen. EAX ist ein Registername. Das E steht für Extended: EAX erweitert AX von 16 auf 32 Bits. Der historische Name Akkumulator ist kein Verbot, andere Register zum Rechnen zu nutzen.",
      "EAX ist nicht in jeder CPU vorhanden. In AArch64 verwenden wir für das Vergleichsbeispiel W0. Registerbezeichnungen sind keine universellen Namen.",
      "Wir beobachten denselben Zustand noch einmal in lesbarer Schreibweise.",
      "1: Die Anweisung als deutschen Satz lesen.",
      sources.intel,
    ),
  ),
  S(
    "Assembly · Zustand beobachten",
    "Zwei Befehle, ein sichtbarer Zustand",
    `<div class="asm-demo"><div>${codeCard("Assembly · unsere Schreibweise", '<span data-asm-line="1">MOV EAX, 5</span>\n<span data-asm-line="2">ADD EAX, 3</span>')}</div><div class="register-note"><span>Register EAX</span><strong data-asm-value>?</strong></div></div>${frag(1, '<p class="mini">Nach MOV EAX, 5: EAX enthält 5.</p>')}${frag(2, '<p class="mini">Nach ADD EAX, 3: EAX enthält 8.</p>')}`,
    "Die lesbaren Befehle beschreiben, was die codierten Maschinenanweisungen bewirken.",
    note(
      "Den Registerzustand synchron zu zwei bekannten Anweisungen ändern.",
      "Welcher Wert steht nach der ersten und nach der zweiten Anweisung in EAX?",
      "Erst 5, dann 8.",
      "Vorher ist der Wert für dieses Beispiel unbekannt. MOV setzt ihn, ADD verändert ihn. Die Hervorhebung zeigt die gerade dargestellte ausgeführte Anweisung. Diese Darstellung zeigt nicht, dass Text direkt in der CPU ausgeführt wird.",
      "Nicht nach beiden Anweisungen zwei dauerhaft nebeneinander liegende Werte im selben Register annehmen.",
      "Wer erzeugt aus diesen lesbaren Befehlen die passenden Bits?",
      "1: MOV und Wert 5. 2: ADD und Wert 8.",
      sources.intel,
    ),
    { demo: "assembly" },
  ),
  S(
    "Assembler · der Übersetzer",
    "Die CPU braucht weiterhin Bits",
    `<div class="translation-chain"><div class="node">Assembly<pre>MOV EAX, 5<br>ADD EAX, 3</pre></div><span class="arrow">→</span><div class="node unknown fragment" data-step="1"><span class="orange">Assembler</span><p class="mini">passende Befehlstabelle</p></div><span class="arrow fragment" data-step="1">→</span><div class="node fragment" data-step="1">Maschinencode<pre>10111000 …<br>10000011 …</pre></div><span class="arrow fragment" data-step="2">→</span><div class="node accent fragment" data-step="2">${icon("cpu")}CPU</div></div>${frag(2, '<p class="mini">Ein <em>Assembler</em> übersetzt Assembly in Maschinencode für den gewählten Befehlssatz.</p>')}`,
    "Assembly ist die Sprache. Der Assembler ist das übersetzende Programm.",
    note(
      "Assembler aus der noch offenen Übersetzungslücke ableiten.",
      "Was fehlt zwischen den lesbaren Wörtern und den CPU-Anweisungen?",
      "Ein Übersetzer, der die Regeln der Architektur kennt.",
      "Ein Assembler setzt die gewählte Syntax und Operanden in passende Codierungen um. Die CPU-Architektur muss gewählt sein. Je nach Werkzeug entsteht zunächst eine Objektdatei; Verknüpfung und Laden können weitere Schritte sein. Für dieses Bild werden diese ausgelassen.",
      "Assembler und Assembly nicht gleichsetzen. Der Assembler ist selbst ein Programm; das Wörterbuch allein ist noch kein Übersetzungsvorgang.",
      "Können wir Sprache, Übersetzer, Ergebnis und Ausführung auseinanderhalten?",
      "1: Übersetzer und Maschinencode. 2: CPU und Definition.",
      sources.intel,
    ),
  ),
  S(
    "Denkpause · Zuordnen",
    "Wer macht hier was?",
    `<div class="grid four"><div class="card"><h3>Assembly</h3>${frag(1, "<p>Lesbare Sprache für Maschinenbefehle</p>")}</div><div class="card"><h3>Assembler</h3>${frag(1, "<p>Übersetzt diese Sprache</p>")}</div><div class="card"><h3>Maschinencode</h3>${frag(1, "<p>Codierte CPU-Anweisungen</p>")}</div><div class="card"><h3>CPU</h3>${frag(1, "<p>Führt diese Anweisungen aus</p>")}</div></div>`,
    "Ordnet zuerst selbst zu: Sprache · Übersetzer · Übersetzung · ausführender Baustein.",
    note(
      "Vier Rollen im bereits aufgebauten Modell unterscheiden.",
      "Was ist Sprache, was Programm, was codiertes Ergebnis und was Hardware?",
      "Assembly, Assembler, Maschinencode, CPU.",
      "Karten zunächst ohne Zuordnung zeigen und Aufgaben verteilen lassen. Danach die Antworten gemeinsam aufdecken. Jede falsche Zuordnung mit einer konkreten Handlung klären.",
      "Maschinencode ist weder der Übersetzer noch die CPU selbst.",
      "Würden wir eine große Anwendung auf dieser Ebene schreiben wollen?",
      "1: Alle Zuordnungen.",
    ),
  ),
  S(
    "Warum höhere Sprachen?",
    "Die Zahlen 1 bis 10 zusammenzählen",
    `<div class="sum-example"><div class="listing-wall"><code><span>01</span> MOV EAX, 0</code><code><span>02</span> ADD EAX, 1</code><code><span>03</span> ADD EAX, 2</code><code><span>04</span> ADD EAX, 3</code><code><span>05</span> ADD EAX, 4</code><code><span>06</span> ADD EAX, 5</code><code><span>07</span> ADD EAX, 6</code><code><span>08</span> ADD EAX, 7</code><code><span>09</span> ADD EAX, 8</code><code><span>10</span> ADD EAX, 9</code><code><span>11</span> ADD EAX, 10</code></div><div><p class="task-banner">Unsere Aufgabe</p><div class="sum-numbers"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span>10</span></div><div class="sum-result">1 + 2 + … + 10 <strong>= 55</strong></div><p class="mini">Schon hier: elf einzelne Maschinenanweisungen. Was wäre bei 1 bis 1.000?</p></div></div>${frag(1, '<p class="mini">Jede Zeile verändert dasselbe Register. Alle gezeigten Anweisungen gehören zu dieser Rechnung.</p>')}`,
    "Viele Einzelschritte lassen sich als eine überschaubare Aufgabe beschreiben.",
    note(
      "Den Abstraktionsbedarf an einer vollständig nachvollziehbaren Rechnung begründen.",
      "Wie wächst die Liste, wenn wir alle Zahlen bis 1.000 so addieren?",
      "Wir bräuchten sehr viele ADD-Zeilen oder eine Wiederholung.",
      "MOV setzt EAX auf 0. Die zehn ADD-Anweisungen addieren nacheinander die Zahlen 1 bis 10, danach enthält EAX 55. Die gesamte Liste ist ein gültiger, bewusst ausgeschriebener Rechenausschnitt. Auch Assembly kann Schleifen ausdrücken; hier zeigen wir die wiederholte Arbeit zunächst ausgeschrieben. Die Datei summe.s enthält genau diese Rechnung.",
      "Nicht behaupten, Assembly müsse jede Wiederholung ausschreiben oder ein Compiler erzeuge zwingend diese elf Anweisungen.",
      "Wie können wir Wiederholen als Absicht aufschreiben?",
      "1: Verbindung zwischen Liste und Rechnung.",
      "",
    ),
  ),
  S(
    "Höhere Programmiersprachen",
    "Eine Wiederholung statt zehn ADD-Zeilen",
    `<p class="task-banner">Dieselbe Aufgabe: alle ganzen Zahlen von 1 bis 10 addieren.</p><div class="grid two">${codeCard("Python", "summe = 0\nfor zahl in range(1, 11):\n    summe = summe + zahl", "compact-code")}<div class="card"><h3>Die Wiederholung in Worten</h3><p>Beginne mit 0.</p><p>Nimm nacheinander die Zahlen 1 bis 10.</p><p>Zähle jede Zahl zur bisherigen Summe.</p><strong class="big mint">55</strong></div></div>${frag(1, '<div class="answer">Drei Python-Zeilen beschreiben die Aufgabe hinter den elf Assembly-Anweisungen.<small>range(1, 11) endet vor 11 und liefert deshalb 1 bis 10.</small></div>')}`,
    "Wir formulieren die Wiederholung, ohne einzelne Register zu benennen.",
    note(
      "Höhere Sprachen mit einem größeren, aber noch nachvollziehbaren Beispiel vergleichen.",
      "Was sagen beide Programme über die Wiederholung?",
      "Nimm jede Zahl von 1 bis 10 und addiere sie zur Summe.",
      "summe bezeichnet den bisherigen Gesamtwert. zahl nimmt nacheinander die Werte 1 bis 10 an. Die eingerückte Python-Zeile wird für jede dieser Zahlen ausgeführt. range schließt die obere Grenze 11 aus. Die Syntax muss hier noch nicht auswendig gelernt werden; es geht um die sichtbare Absicht hinter der Wiederholung.",
      "Eine kurze Quelltextzeile entspricht nicht zwingend einer Maschinenanweisung. Die gezeigte Assembly-Folge war eine mögliche ausgeschriebene Rechnung, kein fest vorgeschriebenes Compilerergebnis.",
      "Das Verbergen einzelner technischer Schritte kennen wir vom Gaspedal.",
      "1: Gemeinsam auflösen.",
      "Python: https://docs.python.org/3/tutorial/controlflow.html#the-range-function",
    ),
  ),
  S(
    "Abstraktion · das Gaspedal",
    "Du bedienst ein Pedal",
    `${scene("gaspedal", "Ein Gaspedal links, darunter beziehungsweise dahinter Sensor, Motorsteuerung und Einspritzung als technische Schritte.")}${frag(1, '<div class="answer">Du gibst einen einfachen Wunsch vor. Das System kümmert sich um die technischen Schritte.</div>')}`,
    "Das Pedal macht komplexe Technik über eine einfache Bedienung zugänglich.",
    note(
      "Abstraktion mit der im Plan genannten anschaulichen Gaspedalmetapher erklären.",
      "Müsst ihr beim Beschleunigen jeden Sensor und jeden Einspritzvorgang einzeln steuern?",
      "Nein, wir benutzen das Pedal.",
      "Die Zeichnung zeigt schematisch einen elektronisch gesteuerten Verbrennungsmotor. Ein Pedalwert wird gemessen und durch die Motorsteuerung verarbeitet. Das Bild ist eine Analogie für die Bedienoberfläche, keine vollständige Kfz-Erklärung und kein garantierter direkter Befehl „Geschwindigkeit erhöhen“.",
      "Ein Pedal steht nicht in jedem Fahrzeug für denselben technischen Mechanismus. Das Beispiel erklärt die Trennung zwischen einfacher Bedienung und inneren Details.",
      "Wie heißt dieses allgemeine Prinzip?",
      "1: Gemeinsames Prinzip aus dem Bild ableiten.",
    ),
  ),
  S(
    "Der neue Begriff · Abstraktion",
    "Details hinter einem einfacheren Konzept",
    `<div class="definition"><em>Abstraktion</em> bedeutet, komplizierte Details hinter einem einfacheren Konzept zu verbergen.</div>${frag(1, '<div class="grid two"><div class="card"><h3>Pedal drücken</h3><p>Viele technische Vorgänge auslösen.</p></div><div class="card"><h3>5 + 3 schreiben</h3><p>Die Berechnung beschreiben, ohne CPU-Register festzulegen.</p></div></div>')}`,
    "Die Details verschwinden nicht. Sie werden auf einer anderen Ebene erledigt.",
    note(
      "Den Namen aus dem konkreten Bild ableiten.",
      "Was haben das Pedal und eine höhere Programmiersprache gemeinsam?",
      "Beide machen etwas Kompliziertes einfacher benutzbar.",
      "Abstraktion lässt uns mit einem passenden Modell arbeiten, statt jede Einzelheit ständig mitzudenken. Die verborgenen Schritte bleiben notwendig. Welche Details verborgen werden, hängt vom Zweck der Abstraktion ab.",
      "Abstraktion ist nicht automatisch Verschleierung, Unwissenheit oder das Wegfallen technischer Arbeit.",
      "Auch eine kurze Ausgabeanweisung nutzt viele verborgene Schichten.",
      "1: Die gemeinsame Struktur beider Beispiele.",
    ),
  ),
  S(
    "Abstraktion im Programm",
    "Ein kleines print – viele Schritte darunter",
    `<div class="abstraction-stack">${codeCard("Python · unser Wunsch", 'print("Hallo")')}<div class="stack-layer fragment" data-step="1"><span>Text verarbeiten</span><span>Speicher verwalten</span></div><div class="stack-layer fragment" data-step="2"><span>Ausgabe an das Betriebssystem geben</span></div><div class="stack-layer fragment" data-step="3"><span>Ausgabeprogramm, Treiber und Hardware</span></div></div>`,
    "print beschreibt die Ausgabe. Die unteren Ebenen machen sie möglich.",
    note(
      "Das Stackbild aus dem Plan in einer gestuften Darstellung zeigen.",
      "Muss in unserer einen Zeile auch jeder Bildpunkt oder jeder Hardwarezugriff stehen?",
      "Nein, darum kümmern sich andere Programme und Schichten.",
      "print gibt an einen Ausgabestrom aus. Ein Ausgabefenster kann den Text darstellen; er könnte auch in eine Datei umgeleitet werden. Betriebssystem bedeutet hier vorerst die grundlegende Software, die Hardware und Dienste organisiert. Treiber vermittelt zu Geräten. Beides wird später genauer behandelt. Die Boxen sind beteiligte Schichten, kein exakter zeitlicher Ablauf aller Implementierungen.",
      "print spricht nicht direkt den Bildschirm an und muss nicht immer sichtbar auf einem Bildschirm enden.",
      "In welcher Form schreiben wir solche Anweisungen?",
      "1: Verarbeitung. 2: Betriebssystem. 3: weitere Schichten.",
      sources.python,
    ),
  ),
  S(
    "Programmiersprache und Quellcode",
    "Was wir schreiben, ist zunächst Text",
    `${codeCard("rechnung.py · Python-Quellcode", "result = 5 + 3\nprint(result)")}${frag(1, '<div class="grid two"><div class="card"><h3>Programmiersprache</h3><p>Eine formale Sprache mit festen Regeln, um Programme zu beschreiben.</p></div><div class="card"><h3>Quellcode</h3><p>Der von Menschen geschriebene Text eines Programms.</p></div></div>')}`,
    "Diese Textzeichen sind noch keine direkt ausführbaren CPU-Anweisungen.",
    note(
      "Programmiersprache und Quellcode am bekannten Zweizeiler unterscheiden.",
      "Was steht in der Datei, bevor wir das Programm ausführen?",
      "Text; unsere Anweisungen in Python.",
      "Die Programmiersprache legt Schreibweise und Bedeutung fest. Der konkrete geschriebene Text heißt Quellcode. In Python bindet result einen Namen an den Ergebniswert; print(result) gibt ihn aus. Die Endung .py ist die übliche Dateiendung für Python-Quellcode.",
      "Eine Datei mit der Endung .py garantiert keinen gültigen Quellcode. Der Text ist nicht bereits das Maschinenprogramm für x86 oder Arm.",
      "Wie kommt ein Text in einer höheren Sprache zur Ausführung?",
      "1: Beide bereits an Beispielen vorbereiteten Begriffe zusammenfassen.",
      sources.python,
    ),
  ),
  S(
    "Compiler · vor der Ausführung übersetzen",
    "Quellcode wird zu konkreten Maschinenanweisungen",
    `<div class="grid two">${codeCard("C · vollständige kleine Funktion", "int ergebnis(void) {\n    return 5 + 3;\n}", "compact-code")}<div><div class="compiler-label">Compiler → Maschinencode</div>${codeCard("Echte Bits · eine optimierte Übersetzung", '<span class="orange">10111000</span> <span class="blue">00001000 00000000\n00000000 00000000</span>\n<span class="orange">11000011</span>', "compact-code")}</div></div>${frag(1, '<div class="grid two"><div class="card"><h3>MOV EAX, 8</h3><p>Ergebniswert 8 bereitstellen.</p></div><div class="card"><h3>RET</h3><p>Zur aufrufenden Stelle zurückkehren.</p></div></div>')}`,
    "Ein Compiler übersetzt ein Programm. Hier erzeugt er Maschinencode für die CPU.",
    note(
      "Den Compiler an vollständigem realem Maschinencode erklären.",
      "Welche Arbeit nimmt uns der Compiler hier ab?",
      "Er macht aus dem Quelltext codierte Maschinenanweisungen.",
      "Die Funktion constant.c wurde mit Clang für x86-64 mit -O2 übersetzt. Ihr Code besteht aus B8 08 00 00 00 C3, also MOV EAX,8; RET. Die fünf ersten Bytes bilden die erste Anweisung, das letzte Byte die Rückkehranweisung. Dies ist der vollständige Code der kleinen Funktion, nicht der Inhalt einer vollständigen Programmdatei. Die Bytes werden in Speicherreihenfolge gezeigt. Compiler können auch andere Zielformen erzeugen; hier betrachten wir nur Maschinencode.",
      "Die Funktionsanweisungen sind noch keine eigenständig startbare Anwendung. Ein Compiler ersetzt nicht einfach jeden Quelltextbuchstaben durch ein festes Bitmuster.",
      "Warum steht hier bereits 8, obwohl im Quellcode 5 + 3 steht?",
      "1: Beide codierten Anweisungen lesbar erläutern.",
      "Intel SDM: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
    ),
  ),
  S(
    "Ein Compiler ist mehr als ein Wörterbuch",
    "Muss die CPU 5 + 3 noch ausrechnen?",
    `<div class="grid two">${codeCard("C · vor dem Übersetzen", "int result(void) {\n  return 5 + 3;\n}", "compact-code")}${frag(1, codeCard("Mögliche optimierte Umsetzung", "Ergebniswert 8 bereitstellen\nZur aufrufenden Stelle zurückkehren", "compact-code"))}</div>${answer(2, "Nicht unbedingt. Der Compiler kann 5 + 3 schon vorher zu 8 vereinfachen.", "Er analysiert Struktur und Bedeutung. Er ersetzt nicht bloß einzelne Wörter durch Bits.")}`,
    "Das Wörterbuch erklärt eine Codierung. Ein Compiler verarbeitet ein ganzes Programm.",
    note(
      "Das Wörterbuchmodell begrenzen und konstante Faltung erklären.",
      "Warum wäre zur Laufzeit noch ein Addieren nötig, wenn beide Werte schon feststehen?",
      "Es ist nicht nötig; man kann vorher 8 berechnen.",
      "Für das mitgelieferte C-Beispiel wurde mit Optimierung kompiliert. Clang erzeugt die direkte Bereitstellung von 8. Das illustriert, dass Quelltext und Maschinenbefehle nicht Wort für Wort zusammenpassen müssen. Optimierungen müssen die zugesagte Bedeutung erhalten.",
      "Nicht behaupten, jeder Compiler optimiere in jeder Konfiguration genauso. Die gewählte Optimierung ist eine mögliche Übersetzung dieses Beispiels.",
      "Muss für jede Sprache zuerst ein eigenes fertiges Maschinenprogramm vorliegen?",
      "1: Mögliche vereinfachte Form. 2: Begründung.",
    ),
  ),
  S(
    "Interpreter · während der Ausführung vermitteln",
    "Buchübersetzung oder Dolmetscher?",
    `${scene("uebersetzen", "Links wird ein komplettes Buch vorher in ein anderes Buch übersetzt. Rechts hilft ein Dolmetscher zwei Menschen während eines Gesprächs.")}${frag(1, '<div class="answer">Ein Interpreter führt ein Programm aus, indem er dessen Anweisungen auswertet und die passenden Aktionen veranlasst.</div>')}`,
    "Eine Analogie für die Arbeitsweise. Reale Systeme kombinieren oft Übersetzung und Interpretation.",
    note(
      "Interpreter mit der konkreten Buch-/Dolmetschermetapher des Plans vorbereiten.",
      "Kann man etwas vermitteln, während eine Handlung bereits läuft?",
      "Ja, wie beim Dolmetschen.",
      "Links steht das vorher erzeugte Übersetzungsergebnis im Vordergrund, rechts eine laufende Vermittlung. Ein Interpreter wertet das Programm aus und führt dessen Bedeutung aus. Er muss nicht jedes Wort einzeln übersetzen, nicht jede Zeile genau einmal bearbeiten und auch nicht zwingend direkt Quelltext interpretieren.",
      "Die Analogie ist kein striktes Entweder-oder. Compilieren und Interpretieren können im selben System vorkommen. Schleifen widersprechen einem starren Zeile-für-Zeile-Bild.",
      "Wer führt die eigentliche Arbeit auch beim Interpretieren aus?",
      "1: Begriff nach dem Bild.",
    ),
  ),
  S(
    "Denkpause · Die CPU bleibt dabei",
    "Braucht ein interpretiertes Programm keine CPU?",
    `<div class="choices"><button class="choice" data-choice><b>A</b>Doch. Auch der Interpreter ist ein Programm, dessen Maschinenanweisungen ausgeführt werden.</button><button class="choice" data-choice><b>B</b>Nein. Der Interpreter ersetzt die Hardware.</button></div>${answer(1, "A · Der Interpreter nutzt die CPU.", "Auch beim Interpretieren führt die CPU Maschinenanweisungen aus.")}`,
    "Ob vorher übersetzt oder beim Ausführen vermittelt: Die CPU bleibt beteiligt.",
    note(
      "Den häufigen falschen Gegensatz zwischen Interpreter und CPU beseitigen.",
      "Wer führt die Arbeit aus, die der Interpreter beim Auswerten benötigt?",
      "Wieder die CPU, über das Interpreterprogramm.",
      "Der Interpreter ist ausführbare Software. Seine Maschinenanweisungen und die von Bibliotheken werden auf einer CPU ausgeführt. Der Quellcode des Anwenderprogramms wird dadurch umgesetzt, ohne selbst als native CPU-Anweisung vorliegen zu müssen.",
      "Nicht aus „interpretiert“ auf eine Ausführung ohne Maschinencode schließen.",
      "Jetzt nehmen wir unser Python-Programm als konkreten Fall.",
      "1: Lösung mit Verbindung zur CPU.",
    ),
  ),
  S(
    "Python · die Rechnung als Quellcode",
    "Unser Beispiel passt in zwei Zeilen",
    `${codeCard("rechnung.py", '<span class="blue">result</span> = 5 + 3\n<span class="orange">print</span>(result)')}${frag(1, '<div class="grid two"><div class="card"><h3>result = 5 + 3</h3><p>Die Rechnung ergibt 8. Der Name result verweist auf diesen Wert.</p></div><div class="card"><h3>print(result)</h3><p>Den Wert ausgeben.</p></div></div>')}`,
    "Wir beschreiben die Rechnung, ohne Register oder CPU-Opcodes auszuwählen.",
    note(
      "Das echte Python-Beispiel mit Bindung und Ausgabe verständlich lesen.",
      "Was macht die erste Zeile, und was ergänzt die zweite?",
      "Rechnen und Ergebnis benennen; anschließend ausgeben.",
      "result ist ein frei gewählter Bezeichner. = bindet den Namen an den Wert rechts; es ist hier eine Zuweisung und keine mathematische Gleichheitsprüfung. print ruft die eingebaute Ausgabefunktion auf. Es reicht, beide Zeilen als Handlung zu erklären; Namenbindung wird später vertieft.",
      "result ist nicht der feste Name eines CPU-Registers. Die erste Zeile allein würde in einer gewöhnlichen Skriptdatei noch nichts ausgeben.",
      "Wie verbinden wir diese Schreibweise mit den bekannten CPU-Anweisungen?",
      "1: Beide Zeilen erklären.",
      sources.python,
    ),
  ),
  S(
    "Python ausführen · vereinfachte Übersicht",
    "Von unserer Rechnung zu CPU-Anweisungen",
    `<div class="translation-chain"><div class="node">Python<pre>result = 5 + 3</pre></div><span class="arrow">→</span>${frag(1, "Übersetzen<small><br>Die Sprachregeln umsetzen</small>", "node accent")}<span class="arrow fragment" data-step="2">→</span>${frag(2, "Maschinenanweisungen<pre>Wert 5 bereitstellen<br>Wert 3 addieren</pre>", "node")}</div>${frag(3, '<div class="answer">Die CPU arbeitet mit codierten Anweisungen. Python beschreibt die Aufgabe.</div>')}`,
    "Vereinfachtes Übersetzungsmodell: Zwischenstufen sind ausgeblendet.",
    note(
      "Python ohne weitere interne Begriffe mit den bekannten Maschinenanweisungen verbinden.",
      "Was beschreiben wir in Python, und was braucht die CPU?",
      "Wir beschreiben 5 + 3; die CPU braucht passende Maschinenanweisungen.",
      "Wir zeigen die Rechenabsicht und eine konkrete mögliche Umsetzung. Die Pfeile fassen die Verarbeitung des Quellcodes bewusst zusammen. Sie sind keine Aufzeichnung einer wörtlichen Übersetzung durch das lokal gestartete Python. Die tatsächliche Ausführung kann mehr Anweisungen und Optimierungen enthalten. Für das Grundverständnis verfolgen wir dieselbe Rechnung auf den bekannten Ebenen.",
      "Python-Text ist kein einzelner CPU-Opcode; eine Variable ist kein fest zugeteilter Registername.",
      "Erkennen wir die drei Schreibweisen wieder?",
      "1: Übersetzung. 2: Konkrete Rechenschritte. 3: Verbindung zur CPU.",
      "",
    ),
  ),
  S(
    "Mini-Quiz · Schreibweisen erkennen",
    "Python, Assembly oder Maschinencode?",
    `<div class="grid three"><div>${codeCard("A", "MOV EAX, 5\nADD EAX, 3", "compact-code")}${frag(1, '<p class="quiz-solution orange">Assembly</p>')}</div><div>${codeCard("B", "result = 5 + 3\nprint(result)", "compact-code")}${frag(2, '<p class="quiz-solution blue">Python</p>')}</div><div>${codeCard("C", "10111000 00000101\n00000000 00000000\n00000000\n10000011 11000000\n00000011", "compact-code")}${frag(3, '<p class="quiz-solution mint">Maschinencode</p>')}</div></div>`,
    "Erst zuordnen und begründen. Dann die Lösungen einzeln aufdecken.",
    note(
      "Die drei eingeführten Darstellungen anhand konkreter Beispiele unterscheiden.",
      "Welche Sprache beziehungsweise Codierung seht ihr auf A, B und C?",
      "A Assembly, B Python, C Maschinencode.",
      "A benennt Operationen und das Register. B beschreibt die Rechnung mit einem Namen und einer Ausgabe. C enthält die echten Bytes der beiden Assembly-Anweisungen von A, nur anders umgebrochen. Der Kontext Maschinencode wurde hier vorgegeben: Eine isolierte Bitfolge verrät ihre Bedeutung nicht von selbst. B enthält zusätzlich eine Ausgabe, die in A und C nicht enthalten ist.",
      "Nicht jede Folge aus Nullen und Einsen ist Maschinencode. Auch Bilder oder Buchstaben sind als Bits gespeichert. Hier kennen wir Befehlssatz und Kontext.",
      "Wir sehen uns die tatsächliche Ausgabe des Python-Programms an.",
      "1: A. 2: B. 3: C.",
      "",
    ),
  ),
  S(
    "Das echte Ergebnis",
    "Vom Python-Programm zur Ausgabe",
    `<div class="grid two">${codeCard("examples/rechnung.py", "result = 5 + 3\nprint(result)")}${frag(1, '<div class="output-window"><div class="code-title">Ausgabe des ausgeführten Programms</div><strong>8</strong></div>')}</div>${frag(2, '<p class="lead">Die zwei Zeilen wurden mit Python ausgeführt.<br><span class="mint">print(result)</span> macht den Wert als Ausgabe sichtbar.</p>')}`,
    "Eine Rechnung liefert einen Wert. print gibt diesen Wert aus.",
    note(
      "Die tatsächliche Ausführung von einer bloßen Browser-Animation unterscheiden.",
      "Was erwarten wir als Ausgabe, bevor wir sie zeigen?",
      "8.",
      "Die mitgelieferte Datei wurde bei der Erstellung mit dem lokalen Python-Interpreter ausgeführt; die aufgezeichnete Standardausgabe steht daneben. Zum eigenen Versuch im examples-Ordner python3 rechnung.py beziehungsweise unter Windows bei entsprechend eingerichtetem Python py rechnung.py ausführen. Befehlsauflösung und Terminal sind Gegenstand des späteren Seminars.",
      "Die Klickanimation führt nicht heimlich Python im Browser aus. Eine Aufzeichnung ist kein frei editierbarer Code-Spielplatz.",
      "Welche Regeln und welche Programme haben von der Idee bis zur Ausgabe geholfen?",
      "1: Tatsächliche Ausgabe. 2: Herkunft und selbst nutzbare Datei.",
      "Eigene Ausführung: examples/rechnung.py und examples/rechnung-ausgabe.txt",
    ),
  ),
  S(
    "Abschluss · 5 + 3 auf drei Ebenen",
    "Python → Assembly → Nullen und Einsen",
    `<div class="final-chain"><div class="final-row"><span class="level-label">1 · Python</span>${codeCard("Die Rechnung beschreiben", "result = 5 + 3", "compact-code")}</div>${frag(1, '<div class="final-row"><span class="level-label">2 · Assembly<br><small>Eine konkrete Umsetzung</small></span>' + codeCard("Die zwei Rechenschritte", '<span class="orange">MOV</span> EAX, <span class="blue">5</span>\n<span class="orange">ADD</span> EAX, <span class="blue">3</span>', "compact-code") + "</div>")}${frag(2, '<div class="final-row"><span class="level-label">3 · Maschinencode<br><small>Exakt diese Assembly-Folge</small></span>' + codeCard("Vollständige Bytes · in Speicherreihenfolge", '<span class="orange">10111000</span> <span class="blue">00000101 00000000 00000000 00000000</span>\n<span class="orange">10000011</span> 11000000 <span class="blue">00000011</span>', "compact-code") + "</div>")}${frag(3, '<div class="final-result">CPU führt aus → Register EAX: <strong class="mint">8</strong><span>00000000 00000000 00000000 00001000</span></div>')}</div>`,
    "Vereinfachtes Übersetzungsmodell · Die Bits entsprechen exakt den gezeigten Assembly-Anweisungen.",
    note(
      "Die Rechnung 5 + 3 konkret bis zur binären Codierung und zum Ergebnis zusammenführen.",
      "Welche Teile erkennen wir auf jeder Ebene wieder?",
      "Die Werte 5 und 3, das Addieren und das Ergebnis 8.",
      "Die Python-Zeile formuliert die Rechnung. Die mittlere Ebene zeigt eine konkrete Umsetzung dieser Rechnung mit MOV und ADD. Die unteren Bytes B8 05 00 00 00 83 C0 03 sind die echte Codierung genau dieser beiden x86-64-Anweisungen. Die erste Anweisung belegt fünf Bytes, die zweite drei. Das Register enthält danach die 32-Bit-Darstellung der Zahl 8. Die Verbindung ab Python ist eine vereinfachte Darstellung derselben Bedeutung, keine gemessene Python-Übersetzung. Zusätzliche Schritte für Programmstart oder Ausgabe sind hier nicht dargestellt.",
      "Ein Python-Name bezeichnet nicht automatisch EAX. Die finale Zeile mit dem Wert 8 ist ein Registerinhalt und keine weitere Maschinenanweisung. Optimierungen können eine Addition durch die direkte Bereitstellung von 8 ersetzen.",
      "Der Hauptteil endet hier. Nur bei Fragen folgt der Exkurs zu Architekturen und Schreibweisen.",
      "1: Assembly. 2: Echte Bits. 3: Registerinhalt.",
      "Intel SDM: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
    ),
  ),
];

const earlyStorage = [
  S(
    "Register · kleine Speicherplätze",
    "Was liegt direkt auf dem Schreibtisch?",
    `${scene("arbeitsplatz", "CPU als Schreibtisch mit zwei kleinen Notizzetteln für Register. Daneben ein größerer Aktenschrank für RAM.")}${frag(1, '<div class="answer">Register sind kleine, schnelle Speicherplätze direkt in der CPU.</div>')}`,
    "Register: Werte griffbereit. RAM: viel mehr Platz, aber nicht direkt auf dem Schreibtisch.",
    note(
      "Die konkrete Schreibtischmetapher des Plans ausarbeiten.",
      "Was würdet ihr griffbereit auf dem Tisch lassen, was in den Aktenschrank legen?",
      "Gerade benötigte Zahlen auf den Tisch; viele andere Inhalte in den Schrank.",
      "Der Rechenstand unserem Beispiel liegt in einem Register. Register sind durch die Architektur sichtbare kleine Speicherplätze für gerade benötigte Werte. RAM ist deutlich größer. Die tatsächliche Hierarchie enthält auch Caches; der Schreibtisch/Aktenschrank-Vergleich ist eine bewusst vereinfachte Analogie.",
      "Ein Python-Variablenname ist später nicht automatisch ein bestimmtes CPU-Register. Die CPU selbst ist kein Speicherort für alle Programmdateien.",
      "Wie findet die CPU einen bestimmten Platz im größeren Arbeitsspeicher?",
      "1: Definition nach der Bildbesprechung.",
    ),
  ),
  S(
    "Speicheradressen · die Hausnummern im RAM",
    "Wo liegt die 8?",
    `<div class="address-street" aria-label="Vier Speicherplätze mit den Adressen 0 bis 3"><div class="memory-house target"><span class="house-number">Adresse 0</span><small>Inhalt</small><strong>8</strong></div><div class="memory-house"><span class="house-number">Adresse 1</span><small>Inhalt</small><strong>5</strong></div><div class="memory-house"><span class="house-number">Adresse 2</span><small>Inhalt</small><strong>12</strong></div><div class="memory-house"><span class="house-number">Adresse 3</span><small>Inhalt</small><strong>0</strong></div></div>${frag(1, '<div class="grid two"><div class="card"><h3 class="blue">Adresse = Wo?</h3><p>Die Nummer bezeichnet einen Speicherplatz.</p></div><div class="card"><h3 class="mint">Inhalt = Was?</h3><p>Der Wert liegt an diesem Platz.</p></div></div>')}`,
    "Wie bei einer Hausnummer: Die Adresse bleibt, der Inhalt kann wechseln.",
    note(
      "Eine Speicheradresse als Ortsangabe vor ihrer Verwendung in Befehlen einführen.",
      "Welche Zahl nennen wir, wenn wir die 8 aus dem ersten Haus holen wollen?",
      "Adresse 0. Die 8 ist der Inhalt.",
      "Die nummerierten Häuser sind Speicherplätze im RAM. Eine Adresse identifiziert einen Platz; sie ist nicht der dort gespeicherte Wert. Man kann bei Adresse 0 heute 8 und später 20 ablegen. Reale Speicher werden meist byteweise adressiert; mehrbyteige Werte belegen mehrere benachbarte Adressen. Für diese erste Ansicht zeigt ein Haus einen Wert. Bei Null zu beginnen ist eine verbreitete Konvention.",
      "Die Hausnummer 0 bedeutet nicht, dass in diesem Haus die Zahl 0 liegen muss. Register sind eigene Speicherplätze in der CPU und keine Häuser dieser RAM-Straße.",
      "Wie hängen das Register auf dem Tisch und die nummerierten Plätze zusammen?",
      "1: Adresse und Inhalt als zwei Begriffe trennen.",
      "",
    ),
  ),
  S(
    "Register und Adresse zusammen",
    "Die 8 vom Tisch in Haus 0",
    `<div class="store-visual"><div class="register-note"><span>CPU · Register</span><strong>8</strong></div><div class="store-arrow"><strong>→</strong><span>an Adresse 0 schreiben</span></div><div class="memory-house target"><span class="house-number">Adresse 0</span><small>Inhalt danach</small><strong class="fragment" data-step="1">8</strong></div></div>${frag(2, '<div class="answer">Die Adresse sagt wohin. Das Register liefert den Wert.<small>Die 8 bleibt auch im Register, bis eine weitere Anweisung sie verändert.</small></div>')}`,
    "Lesen holt einen Inhalt. Schreiben legt einen Inhalt an einer Adresse ab.",
    note(
      "Den späteren STORE-Befehl als konkrete Handlung vorbereiten.",
      "Müssen wir für das Ablegen die Hausnummer 0 oder den Inhalt 8 angeben?",
      "Den Zielplatz 0; die 8 steht schon im Register.",
      "Wir lassen den Registerinhalt 8 an Adresse 0 schreiben. Das Schreiben ist eine Kopie des Wertes; die 8 wird nicht vom Tisch entfernt. Der blaue Adresszettel bleibt 0. Nach demselben Prinzip findet eine CPU auch gespeicherte Anweisungen anhand ihrer Position. Im folgenden kleinen Beispiel sind Datenplätze und Anweisungsplätze getrennt nummeriert.",
      "Ein Registername wie EAX und eine RAM-Adresse sind unterschiedliche Arten, Speicherplätze zu bezeichnen. Eine Adresse legt für sich noch keine Operation fest.",
      "Jetzt geben wir solchen Handlungen feste Befehlscodes.",
      "1: 8 erscheint im Ziel. 2: Wert und Ziel auseinanderhalten.",
      "",
    ),
  ),
];

// Ersten Abschnitt bewahren, die Konventionsidee früher einbauen und dann fortsetzen.
const originalSlides = slides.slice();
slides.splice(
  0,
  slides.length,
  ...originalSlides.slice(0, 14),
  ...conventions,
  ...earlyStorage,
  ...originalSlides.slice(14, 20),
  ...construction,
  originalSlides[21],
  ...continuation,
  ...architectures,
);
slides[0].lead = "Von Bits zu Python";
slides[0].notes.explain =
  "Erst sammeln, nichts vorschnell korrigieren. Hardware bedeutet die anfassbaren Teile. Wir verfolgen die Rechnung 5 + 3 von elektronischen Zuständen bis zu Python. Das Bild wird schrittweise präzisiert. Je nach Diskussion zwei Lernblöcke mit Pause nach dem manuell konstruierten Maschinenprogramm einplanen.";

originalSlides[13].notes.transition =
  "Können dieselben Bits auch etwas anderes als eine Zahl darstellen?";
originalSlides[19].notes.transition =
  "Jetzt bauen wir die gesamte Rechnung von Hand aus vollständigen Anweisungen.";
originalSlides[21].eyebrow = "Denkpause · Maschinenbefehl oder Lesehilfe";

// Der Exkurs bleibt nach dem Abschluss und lässt sich gezielt anspringen.
const mainEnd = slides.indexOf(continuation[continuation.length - 1]);
const excursionStart = mainEnd + 1;
slides[mainEnd].bottom +=
  ` <a class="deck-link" href="#${excursionStart + 1}/0">Optional: Architektur-Exkurs →</a>`;
for (const slide of architectures)
  slide.bottom += ` <a class="deck-link" href="#${mainEnd + 1}/3">← Zur Abschlussrechnung</a>`;
