"use strict";

// Fortsetzung des Hauptpfads: Betriebssystem, Prozess, Terminal, Shell und PowerShell.
const systemSources = {
  terminal:
    "Microsoft Learn, Windows Terminal: https://learn.microsoft.com/windows/terminal/",
  terminalFaq:
    "Microsoft Learn, Terminal und Shell: https://learn.microsoft.com/windows/terminal/faq",
  precedence:
    "Microsoft Learn, PowerShell-Befehlsauflösung: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_command_precedence",
  aliases:
    "Microsoft Learn, PowerShell-Aliase: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_aliases",
  path: "Microsoft Learn, Umgebungsvariablen: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_environment_variables",
  redirection:
    "Microsoft Learn, Umleitung: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_redirection",
  member:
    "Microsoft Learn, Get-Member: https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/get-member",
  processes:
    "Microsoft Learn, Prozesse erzeugen: https://learn.microsoft.com/windows/win32/procthread/creating-processes",
};

const systemNote = (
  goal,
  question,
  expected,
  explain,
  misconception,
  transition,
  steps = "Gemeinsam betrachten, dann die Kernaussage aufdecken.",
  source = "",
) =>
  note(
    goal,
    question,
    expected,
    explain,
    misconception,
    transition,
    steps,
    source,
  );

const terminalWindow = (prompt, output = "", title = "PowerShell") =>
  `<div class="terminal-window"><div class="terminal-bar"><span></span><span></span><span></span><b>${title}</b></div><pre><span class="prompt">PS C:\\Seminar&gt;</span> ${prompt}${output ? `\n<span class="terminal-output">${output}</span>` : ""}</pre></div>`;

const systemSlides = [
  S(
    "Historische Entwicklung · Abstraktion",
    "Jede Stufe versteckt mehr Einzelarbeit",
    `<div class="abstraction-stairs"><div><small>direkt an der Hardware</small><strong>Schalter und Steckfelder</strong></div>${frag(1, "<strong>Maschinencode</strong><small>Bits nach dem Befehlssatz</small>", "stair-step")}${frag(2, "<strong>Assembly</strong><small>lesbare Namen für CPU-Befehle</small>", "stair-step")}${frag(3, "<strong>Höhere Sprachen</strong><small>Aufgaben und Abläufe beschreiben</small>", "stair-step")}${frag(4, "<strong>Python</strong><small>wenig technische Einzelheiten im Quellcode</small>", "stair-step")}</div>`,
    "Die unteren Schichten bleiben vorhanden, auch wenn wir sie nicht ständig sehen.",
    systemNote(
      "Die bisherige Geschichte als wachsende Abstraktion zusammenfassen.",
      "Welche Arbeit nimmt jede neue Stufe Menschen ab?",
      "Bitmuster merken, Register auswählen und viele Einzelschritte aufschreiben.",
      "Die Treppe zeigt eine didaktische Entwicklung, keine einzige geradlinige Erfindungsgeschichte. Frühe Systeme wurden unter anderem mit Schaltern und Steckfeldern vorbereitet. Höhere Sprachen beschreiben größere Zusammenhänge. Übersetzer und weitere Software verbinden sie mit ausführbaren Maschinenanweisungen.",
      "Höhere Stufen ersetzen die Hardware nicht. Assembly und Maschinencode werden weiterhin für passende Aufgaben verwendet.",
      "Wann kamen diese Ideen ungefähr auf?",
      "1 bis 4: Die Stufen nacheinander ergänzen.",
    ),
  ),
  S(
    "Historische Entwicklung · Orientierung",
    "Vom Maschinenraum zur Alltagssprache",
    `<div class="system-timeline"><div><span>1940er</span><strong>Schalter, Steckfelder, Maschinencode</strong></div>${frag(1, "<span>1950er</span><strong>Assembly und erste Compiler</strong>", "timeline-entry")}${frag(2, "<span>1960er bis 1980er</span><strong>Betriebssysteme und interaktive Terminals</strong>", "timeline-entry")}${frag(3, "<span>ab 1990</span><strong>Python und verbreitete grafische Systeme</strong>", "timeline-entry")}</div>`,
    "Die Techniken überlappen sich. Neue Ebenen bauen auf älteren auf.",
    systemNote(
      "Eine grobe zeitliche Orientierung geben, ohne Technikgeschichte als exakte Ablösung darzustellen.",
      "Sind alte Ebenen verschwunden, sobald eine neue erfunden wurde?",
      "Nein, sie bleiben unterhalb oder in besonderen Einsatzgebieten erhalten.",
      "Die Jahresbereiche sind grobe Orientierung. Compiler und Betriebssystemideen entwickelten sich in vielen Projekten parallel. Terminals machten die Arbeit interaktiv. Python erschien Anfang der 1990er Jahre und steht hier stellvertretend für zugänglichere Hochsprachen.",
      "Nicht behaupten, alle Computer einer Epoche hätten dieselbe Bedienform gehabt.",
      "Können wir unsere Ebenen nun in eine sinnvolle Reihenfolge bringen?",
      "1 bis 3: Zeitabschnitte ergänzen.",
    ),
  ),
  S(
    "Denkpause · Ebenen ordnen",
    "Vom Quellcode bis zur Ausführung",
    `<div class="sort-pool"><span>CPU</span><span>Assembly</span><span>Compiler</span><span>Python-Quellcode</span><span>Maschinencode</span></div>${answer(1, "Python-Quellcode → Compiler oder Übersetzer → Assembly → Maschinencode → CPU", "Assembly kann als sichtbare Zwischenstufe auftreten. Ein Werkzeug kann sie auch intern überspringen.")}`,
    "Die Reihenfolge beschreibt eine mögliche Übersetzungskette.",
    systemNote(
      "Die Rollen von Beschreibung, Übersetzung, Codierung und Hardware wiederholen.",
      "Welche Karten sind Sprache, Übersetzer, Ergebnis und ausführende Hardware?",
      "Quellcode und Assembly sind Sprachen, der Compiler übersetzt, Maschinencode wird ausgeführt, die CPU führt aus.",
      "Die Auflösung zeigt eine mögliche Kette. Ein Compiler muss keine lesbare Assemblydatei erzeugen. Für Python bleibt dies unser bewusst vereinfachtes Übersetzungsmodell.",
      "Die Abfolge darf nicht als Garantie für jedes Werkzeug verstanden werden.",
      "Wer organisiert nun, dass ein fertiges Programm überhaupt startet?",
      "1: Auflösung nach der gemeinsamen Sortierung.",
    ),
  ),
  S(
    "Betriebssystem · die offene Lücke",
    "Wer startet das Programm?",
    `<div class="flow"><div class="node">Doppelklick<br><small>oder Befehl</small></div><span class="arrow">→</span><div class="node unknown">?</div><span class="arrow">→</span><div class="node">Programmdatei</div><span class="arrow">→</span><div class="node accent">laufende Ausführung</div></div>${frag(1, '<p class="lead">Zwischen unserer Startaktion und der CPU muss jemand Dateien, Speicher und Geräte koordinieren.</p>')}`,
    "Diese Aufgabe übernimmt das Betriebssystem.",
    systemNote(
      "Das Betriebssystem als Antwort auf eine konkrete offene Frage motivieren.",
      "Kann ein Doppelklick selbst Speicher reservieren und CPU-Zeit verteilen?",
      "Nein, eine zentrale Softwareebene muss den Start organisieren.",
      "Ein Doppelklick wird von der grafischen Oberfläche verarbeitet. Das Betriebssystem und beteiligte Systemprogramme ermitteln die passende Datei, laden benötigte Teile und richten die Ausführung ein. Die Details werden auf den nächsten Folien gestuft.",
      "Die CPU entscheidet nicht selbst, welche Anwendung der Mensch gerade öffnen wollte.",
      "Welche Aufgaben bündelt ein Betriebssystem außerdem?",
      "1: Die Lücke als Betriebssystem ankündigen.",
    ),
  ),
  S(
    "Betriebssystem · Grundbegriff",
    "Der Organisator des Computers",
    `<div class="os-orbit"><div class="os-core">Betriebs-<br>system</div><div class="orbit-item o1">Programme starten</div><div class="orbit-item o2">Speicher zuteilen</div><div class="orbit-item o3">Dateien verwalten</div><div class="orbit-item o4">Geräte ansprechen</div></div>${frag(1, '<div class="definition">Ein <em>Betriebssystem</em> verwaltet Computerressourcen und stellt Programmen grundlegende Dienste bereit.</div>')}`,
    "Windows, macOS und Linux sind Beispiele für Betriebssystemfamilien.",
    systemNote(
      "Das Betriebssystem über sichtbare Aufgaben definieren.",
      "Welche Dinge müssen sich mehrere gleichzeitig laufende Programme teilen?",
      "CPU-Zeit, Arbeitsspeicher, Dateien und Geräte.",
      "Das Betriebssystem koordiniert gemeinsam genutzte Ressourcen. Es stellt Programmen Schnittstellen für Dateien, Speicher, Netzwerk und Geräte bereit. Grafische Oberfläche und Systemwerkzeuge gehören zur praktischen Umgebung, auch wenn der technische Kern nur ein Teil des gesamten Betriebssystems ist.",
      "Betriebssystem nicht mit dem Desktopbild oder dem Herstellerlogo gleichsetzen.",
      "Schauen wir uns einen Programmstart konkret an.",
      "1: Definition nach der Bildbesprechung.",
    ),
  ),
  S(
    "Programmstart · vereinfacht",
    "Was Windows beim Start vorbereitet",
    `<div class="grid four sequence"><div class="card"><h3>Datei finden</h3><p>Welche Programmdatei soll laufen?</p></div>${frag(1, "<h3>Code laden</h3><p>Benötigte Teile kommen in den Arbeitsspeicher.</p>", "card")}${frag(2, "<h3>Speicher einrichten</h3><p>Das laufende Programm bekommt einen eigenen Bereich.</p>", "card")}${frag(3, "<h3>Ausführung starten</h3><p>Die CPU erhält ausführbare Maschinenanweisungen.</p>", "card")}</div>`,
    "Aus einer gespeicherten Programmdatei entsteht eine laufende Instanz.",
    systemNote(
      "Den Programmstart als nachvollziehbare Folge zeigen.",
      "Welcher Schritt muss vor dem Ausführen passieren?",
      "Die Datei muss gefunden und ausführbarer Code bereitgestellt werden.",
      "Windows erzeugt beim Start einen Prozess, richtet dessen virtuellen Adressraum und weitere Verwaltungsdaten ein und startet mindestens einen Ausführungsfaden. Für Einsteiger bündeln wir dies unter Speicher einrichten und Ausführung starten. Bibliotheken können zusätzlich geladen werden.",
      "Nicht behaupten, immer werde die vollständige Datei auf einmal in den RAM kopiert.",
      "Wie nennen wir die laufende Instanz?",
      "1 bis 3: Die Startschritte nacheinander aufdecken.",
      systemSources.processes,
    ),
  ),
  S(
    "Programm und Prozess",
    "Datei oder laufende Instanz?",
    `<div class="grid two"><div class="program-file">${icon("file")}<h3>Programm</h3><code>editor.exe</code><p>Gespeicherte Datei mit Anweisungen und Daten.</p></div><div class="process-card running"><span class="process-dot"></span><h3>Prozess</h3><code>PID 4820</code><p>Eine laufende Instanz mit Speicher und Zustand.</p></div></div>${answer(1, "Programm = gespeicherte Grundlage<br>Prozess = laufende Instanz dieses Programms")}`,
    "Eine Programmdatei kann gar nicht, einmal oder mehrfach laufen.",
    systemNote(
      "Programm und Prozess mit sichtbaren Zuständen trennen.",
      "Was verändert sich beim Start?",
      "Zur Datei kommt ein laufender Zustand mit Speicher und einer Kennung hinzu.",
      "Ein Prozess ist eine vom Betriebssystem verwaltete laufende Instanz. Die Prozess-ID, kurz PID, unterscheidet laufende Prozesse. Derselbe Programmcode kann von mehreren Prozessen verwendet werden, während jeder Prozess eigenen Zustand besitzt.",
      "Ein Prozess ist nicht einfach die Programmdatei an einem anderen Speicherort.",
      "Was passiert bei mehreren unabhängigen Starts derselben Datei?",
      "1: Definition aufdecken.",
    ),
  ),
  S(
    "Denkpause · Programm oder Prozess",
    "Dreimal starten, was entsteht?",
    `<div class="one-to-many"><div class="program-file compact">${icon("file")}<strong>editor.exe</strong><small>eine Programmdatei</small></div><span class="arrow">→</span><div class="process-stack"><div>PID 4820</div><div>PID 6312</div><div>PID 7044</div></div></div>${answer(1, "Eine Programmdatei, drei laufende Prozesse.", "Moderne Anwendungen dürfen Starts auch zusammenführen. Das Beispiel setzt drei unabhängige Instanzen voraus.")}`,
    "Die konkrete Prozessstruktur hängt von der Anwendung ab.",
    systemNote(
      "Das Verhältnis von Programmdatei zu Prozessen prüfen.",
      "Sind drei gestartete Instanzen automatisch drei verschiedene Programme?",
      "Nein, sie können auf derselben Programmdatei beruhen.",
      "Im Gedankenbeispiel startet das Betriebssystem dieselbe Datei dreimal unabhängig. Dadurch entstehen drei Prozesse mit eigenen IDs und Zuständen. Manche moderne Anwendungen nutzen mehrere Prozesse für eine Instanz oder führen mehrere Fenster in einem Prozess. Das ändert die Grundunterscheidung nicht.",
      "Fensterzahl und Prozesszahl nicht allgemein gleichsetzen.",
      "Auf welchen Wegen können wir Programme starten?",
      "1: Antwort und Einschränkung.",
    ),
  ),
  S(
    "Programme starten · verschiedene Oberflächen",
    "Drei Wege, dieselbe Absicht",
    `<div class="grid three launch-grid"><div class="card"><span class="launch-icon">↖</span><h3>Doppelklick</h3><p>Eine grafische Oberfläche meldet die Auswahl.</p></div><div class="card"><span class="launch-icon">⌕</span><h3>Startmenü</h3><p>Windows findet die Anwendung über ihren Eintrag.</p></div><div class="card"><span class="launch-icon">&gt;_</span><h3>Textbefehl</h3><p>Wir schreiben Namen und Argumente.</p></div></div>${frag(1, '<div class="answer">Alle Wege enden beim Betriebssystem, das eine Ausführung vorbereitet.</div>')}`,
    "Für Textbefehle brauchen wir eine Ein- und Ausgabeoberfläche.",
    systemNote(
      "Den Terminalpfad aus vertrauten Startwegen ableiten.",
      "Welcher Weg eignet sich besonders für genaue, wiederholbare Abläufe?",
      "Textbefehle, weil sie sich speichern, kopieren und kombinieren lassen.",
      "Grafische und textbasierte Oberflächen lösen letztlich Systemaktionen aus. Textbefehle sind nicht automatisch besser, eignen sich aber gut für Automatisierung und genaue Wiederholung.",
      "Terminalbedienung nicht als einzigen professionellen Weg darstellen.",
      "Was bedeutete Terminal ursprünglich?",
      "1: Gemeinsamer Endpunkt.",
    ),
  ),
  S(
    "Terminal · historische Bedeutung",
    "Ein Bildschirm am Ende einer Leitung",
    `<div class="historical-terminal"><img src="assets/historisches-terminal.png" alt="Illustration eines historischen Textterminals mit Röhrenbildschirm, Tastatur und Kabel zu einem entfernten Großrechner"><div><p class="term">TERMINAL = ENDSTELLE</p><h3>Der große Computer stand oft woanders.</h3>${frag(1, "<p>Das Terminal schickte Tastatureingaben und zeigte die zurückkommenden Zeichen.</p>")}${frag(2, '<p class="mini">Es war vor allem Ein- und Ausgabe, nicht der eigentliche Rechenrechner.</p>')}</div></div>`,
    "Terminal bezeichnete die Endstelle der Verbindung zum Computer.",
    systemNote(
      "Die ursprüngliche Bedeutung von Terminal bildlich verankern.",
      "Wo rechnet das gezeigte Gerät hauptsächlich?",
      "Der entfernte Computer übernimmt die Hauptarbeit.",
      "Frühe interaktive Terminals ersetzten Fernschreiber und stapelweise Eingaben für viele Aufgaben. Sie übertrugen Zeichen über eine Verbindung und stellten Antworten dar. Manche Geräte besaßen lokale Funktionen, doch die zentrale Programmausführung lag häufig auf einem größeren Rechner.",
      "Ein historisches Terminal nicht pauschal als völlig funktionslose Tastatur bezeichnen.",
      "Welche Aufgabe hat ein heutiges Terminalprogramm?",
      "1: Zeichenweg. 2: Abgrenzung zur Rechenmaschine.",
      "Bild mit OpenAI ImageGen erstellt; fachliche Einordnung: " +
        systemSources.terminalFaq,
    ),
  ),
  S(
    "Terminal · heute",
    "Das Fenster für Textprogramme",
    `<div class="grid two"><div>${terminalWindow("Get-Date", "Samstag, 20. September 2026 14:32:10", "Windows Terminal")}</div><div class="terminal-role"><div>Tastatureingabe</div><span>↓</span><strong>Terminal</strong><span>↓</span><div>Textdarstellung</div></div></div>${frag(1, '<div class="definition">Ein <em>Terminal</em> ist eine textbasierte Ein- und Ausgabeoberfläche.</div>')}`,
    "Windows Terminal zeigt Text an. Ein anderes Programm deutet den Befehl.",
    systemNote(
      "Das heutige Terminal als Host für textbasierte Programme definieren.",
      "Welche zwei sichtbaren Aufgaben übernimmt das Fenster?",
      "Eingaben entgegennehmen und Ausgaben darstellen.",
      "Windows Terminal ist eine Host-Anwendung für Kommandozeilenprogramme. Es kümmert sich unter anderem um Fenster, Tabs, Schrift und Darstellung. Darin kann PowerShell, die Eingabeaufforderung oder eine WSL-Shell laufen.",
      "Das Terminal nicht mit der darin laufenden Shell gleichsetzen.",
      "Wer versteht dann Get-Date oder dir?",
      "1: Definition aufdecken.",
      systemSources.terminal,
    ),
  ),
  S(
    "Denkpause · Terminal",
    "Versteht Windows Terminal den Befehl dir?",
    `<div class="choices"><button class="choice" data-choice><b>A</b>Ja, das Terminal entscheidet selbst, welche Dateien gemeint sind.</button><button class="choice" data-choice><b>B</b>Nein, es reicht den Text an das darin laufende Kommandozeilenprogramm weiter.</button></div>${answer(1, "B · Das Terminal zeigt Zeichen und transportiert Eingaben.", "PowerShell oder eine andere Shell interpretiert den Befehl.")}`,
    "Damit fehlt uns noch das Programm, das Befehle versteht.",
    systemNote(
      "Terminal und Befehlsinterpretation trennen.",
      "Was würde beim Wechsel von PowerShell zu cmd im selben Terminalfenster anders?",
      "Die Shellregeln und verfügbaren Befehle ändern sich.",
      "Windows Terminal kann verschiedene Profile öffnen. Jedes Profil startet ein Kommandozeilenprogramm. Das Terminalfenster kann gleich aussehen, obwohl die Shell andere Syntax und Befehle verwendet.",
      "Ein identisches Fenster beweist nicht, dass dieselbe Shell läuft.",
      "Der fehlende Begriff lautet Shell.",
      "Auswählen, begründen, dann 1: Auflösung.",
      systemSources.terminalFaq,
    ),
  ),
  S(
    "Shell · Befehle verstehen",
    "Das Programm hinter der Eingabezeile",
    `<div class="flow"><div class="node">Text<br><code>Get-Date</code></div><span class="arrow">→</span><div class="node accent">Shell<br><small>analysiert den Befehl</small></div><span class="arrow">→</span><div class="node">passende Aktion</div></div>${frag(1, '<div class="definition">Eine <em>Shell</em> ist ein Programm, das Befehle interpretiert und ausführt.</div>')}${frag(2, '<p class="mini">Beispiele: PowerShell, cmd.exe, Bash und Zsh.</p>')}`,
    "Wir arbeiten im Folgenden mit PowerShell.",
    systemNote(
      "Shell als eigenständiges Programm definieren.",
      "Welche Aufgabe geht über bloßes Anzeigen hinaus?",
      "Befehle erkennen, Argumente zuordnen und Aktionen auslösen.",
      "Eine Shell liest Befehle nach ihren Sprachregeln. Sie kann eigene Befehle ausführen, Funktionen aufrufen oder externe Programme starten. Das Betriebssystem führt die angeforderten Systemaktionen aus.",
      "Shell nicht mit Betriebssystem oder Terminal verwechseln.",
      "Wie liegen Terminal und Shell ineinander?",
      "1: Definition. 2: Beispiele.",
      systemSources.terminalFaq,
    ),
  ),
  S(
    "Terminal und Shell",
    "Fenster außen, Befehlsprogramm innen",
    `<div class="terminal-shell"><div class="terminal-frame"><span>Windows Terminal</span><div class="shell-tabs"><b>PowerShell</b><i>cmd</i><i>Ubuntu / Bash</i></div><div class="shell-inside"><code>PS C:\\Seminar&gt; _</code><p>Aktive Shell: PowerShell</p></div></div></div>${answer(1, "Dasselbe Terminal kann verschiedene Shells beherbergen.", "Ein neuer Tab darf andere Befehlsregeln verwenden.")}`,
    "Terminal = Oberfläche. Shell = Befehlsprogramm.",
    systemNote(
      "Die beiden Begriffe räumlich und funktional unterscheiden.",
      "Was bleibt gleich, wenn wir im nächsten Tab cmd statt PowerShell öffnen?",
      "Das Terminalprogramm bleibt, die Shell wechselt.",
      "Windows Terminal verwaltet Tabs und Darstellung. Jedes Profil startet ein Kommandozeilenprogramm. PowerShell und cmd können im selben Fenster laufen, interpretieren Eingaben aber nach unterschiedlichen Regeln.",
      "Ein Tabtitel allein ist kein technischer Beweis; er dient hier als klare Visualisierung.",
      "Prüfen wir die Zuordnung an Beispielen.",
      "1: Kernaussage.",
      systemSources.terminal,
    ),
  ),
  S(
    "Denkpause · Terminal oder Shell",
    "Welche Rolle hat welches Programm?",
    `<div class="grid four"><div class="card"><h3>Windows Terminal</h3>${frag(1, '<p class="blue">Terminal</p>')}</div><div class="card"><h3>PowerShell</h3>${frag(2, '<p class="orange">Shell</p>')}</div><div class="card"><h3>cmd.exe</h3>${frag(2, '<p class="orange">Shell</p>')}</div><div class="card"><h3>Bash</h3>${frag(2, '<p class="orange">Shell</p>')}</div></div>`,
    "Erst selbst zuordnen, dann die Rollen aufdecken.",
    systemNote(
      "Terminal und Shell sicher erkennen.",
      "Welches Programm kümmert sich vor allem um das Fenster?",
      "Windows Terminal.",
      "PowerShell, cmd.exe und Bash sind Shells. Windows Terminal ist ein Terminalprogramm, das diese Kommandozeilenprogramme hosten kann.",
      "Die historische Bezeichnung Windows Console Host nicht zusätzlich einführen.",
      "Nun verfolgen wir einen einzelnen PowerShell-Befehl.",
      "1: Terminal. 2: Shells.",
      systemSources.terminalFaq,
    ),
  ),
  S(
    "PowerShell · erster Befehl",
    "Was passiert bei Get-Date?",
    `${terminalWindow('<span class="orange">Get</span>-<span class="blue">Date</span>', "Samstag, 20. September 2026 14:32:10")}${frag(1, '<div class="grid two"><div class="card"><h3>Get</h3><p>Etwas abrufen.</p></div><div class="card"><h3>Date</h3><p>Das bezeichnete Thema: Datum und Uhrzeit.</p></div></div>')}`,
    "Get-Date ist ein PowerShell-Befehl. Die Ausgabe ist hier ein Beispiel.",
    systemNote(
      "Den ersten PowerShell-Befehl ohne Syntaxballast lesen.",
      "Was vermutet ihr anhand des Namens?",
      "Datum und Uhrzeit abrufen.",
      "PowerShell verwendet für viele Befehle das Muster Verb-Nomen. Get-Date liefert ein Datumsobjekt, das PowerShell für die Anzeige formatiert. Die konkrete Ausgabe hängt von Zeitpunkt, Sprache und Systemeinstellungen ab.",
      "Die Beispielzeit nicht als Ergebnis jedes Rechners ausgeben.",
      "Welche Stationen durchläuft dieser Text?",
      "1: Namensbestandteile.",
    ),
  ),
  S(
    "Get-Date · der Ablauf",
    "Vom Tastendruck zur sichtbaren Uhrzeit",
    `<div class="command-route"><div>Tastatur<small>Zeichen eingeben</small></div><span>→</span>${frag(1, "Windows Terminal<small>Text weiterreichen</small>", "route-step")}${frag(2, "PowerShell<small>Get-Date erkennen</small>", "route-step")}${frag(3, "Befehl ausführen<small>Datumswert erzeugen</small>", "route-step")}${frag(4, "Windows Terminal<small>Ausgabe darstellen</small>", "route-step")}</div>`,
    "Terminal transportiert und zeigt. PowerShell versteht und veranlasst.",
    systemNote(
      "Terminal, Shell und Befehl in einem konkreten Ablauf verbinden.",
      "An welcher Station bekommt Get-Date seine PowerShell-Bedeutung?",
      "Bei PowerShell.",
      "Das Terminal liefert die eingegebenen Zeichen an PowerShell. PowerShell löst den Namen auf, führt das Cmdlet aus und formatiert dessen Ergebnis für den Host. Das Terminal stellt die zurückkommenden Zeichen dar.",
      "Die Darstellung ist eine logische Kette und kein vollständiger interner Protokollablauf.",
      "Sind alle PowerShell-Befehle vom gleichen Typ?",
      "1 bis 4: Stationen ergänzen.",
    ),
  ),
  S(
    "PowerShell · Befehlsarten",
    "Ein Name kann zu Verschiedenem führen",
    `<div class="grid four command-kinds"><div class="card"><h3>Cmdlet</h3><code>Get-Date</code><p>PowerShell-Befehl</p></div><div class="card"><h3>Alias</h3><code>dir</code><p>anderer Name</p></div><div class="card"><h3>Funktion</h3><code>prompt</code><p>definierter Ablauf</p></div><div class="card"><h3>Externes Programm</h3><code>git.exe</code><p>eigene Datei</p></div></div>${frag(1, '<p class="mini">PowerShell löst den eingegebenen Namen nach festen Regeln auf.</p>')}`,
    "Mit Get-Command lässt sich die gefundene Befehlsart anzeigen.",
    systemNote(
      "Vier häufige Befehlsarten als Vorbereitung für Cmdlets, Aliase und externe Programme zeigen.",
      "Welche dieser Arten braucht zwingend eine separate Programmdatei?",
      "Das externe Programm.",
      "Cmdlets stammen aus PowerShell-Modulen. Funktionen können in der Sitzung definiert sein. Aliase verweisen auf andere Befehle. Externe Programme sind eigenständige ausführbare Dateien. PowerShell prüft bei Namenskonflikten Alias, Funktion, Cmdlet und schließlich externe Programme.",
      "Ein sichtbarer Name verrät seine Befehlsart nicht immer sicher.",
      "Beginnen wir mit Cmdlets.",
      "1: Befehlsauflösung ankündigen.",
      systemSources.precedence,
    ),
  ),
  S(
    "Cmdlets · PowerShell-Befehle",
    "Kleine Werkzeuge mit festen Namen",
    `<div class="grid three"><div class="card"><code class="big-code">Get-Date</code><p>Datum und Uhrzeit abrufen</p></div><div class="card"><code class="big-code">Get-Process</code><p>laufende Prozesse abrufen</p></div><div class="card"><code class="big-code">Get-ChildItem</code><p>Inhalte eines Ortes abrufen</p></div></div>${frag(1, '<div class="definition"><em>Cmdlets</em> sind speziell für PowerShell entwickelte Befehle.</div>')}`,
    "Aussprache: Command-lets. Für das Verständnis reicht zunächst: PowerShell-Befehle.",
    systemNote(
      "Cmdlets an drei konkreten Namen einführen.",
      "Welcher Teil wiederholt sich und was verrät er?",
      "Get; der Befehl ruft etwas ab.",
      "Cmdlets folgen meist einer einheitlichen Benennung und geben strukturierte Objekte aus. Sie werden über PowerShell-Module bereitgestellt. Der Fachbegriff darf gesprochen Command-let lauten; wichtiger ist die wiedererkennbare Aufgabe.",
      "Nicht jeden PowerShell-Befehl als Cmdlet bezeichnen.",
      "Wie hilft das Namensmuster beim Erraten neuer Befehle?",
      "1: Definition.",
    ),
  ),
  S(
    "Cmdlets · Verb und Nomen",
    "Der Name beschreibt Handlung und Thema",
    `<div class="verb-noun"><div><span>Verb</span><strong class="orange">Get</strong><p>Was soll passieren?</p></div><i>-</i><div><span>Nomen</span><strong class="blue">Process</strong><p>Womit?</p></div></div>${frag(1, '<div class="grid two"><div class="card"><code>Get-Process</code><p>Prozesse anzeigen.</p></div><div class="card"><code>Stop-Process</code><p>Einen Prozess stoppen.</p></div></div>')}`,
    "Das Muster macht viele Namen vorhersagbar.",
    systemNote(
      "Das Verb-Nomen-Muster als Orientierungshilfe erklären.",
      "Wie könnte ein Befehl zum Stoppen eines Prozesses heißen?",
      "Stop-Process.",
      "PowerShell verwendet genehmigte Verben und Nomen im Singular. Das Muster hilft beim Suchen und Lesen. Ein Befehl braucht häufig zusätzliche Angaben, etwa welchen Prozess er stoppen soll. Das folgt später.",
      "Aus dem Namen allein folgen nicht automatisch alle erforderlichen Parameter oder Berechtigungen.",
      "Warum funktionieren trotzdem kurze Namen wie dir?",
      "1: Beispiele aufdecken.",
    ),
  ),
  S(
    "Alias · ein zweiter Name",
    "Drei Eingaben, derselbe PowerShell-Befehl",
    `<div class="alias-lines"><code>Get-ChildItem</code>${frag(1, "<code>dir</code>")}${frag(2, "<code>ls</code>")}</div>${frag(3, '<div class="answer">In PowerShell verweisen dir und ls standardmäßig auf Get-ChildItem.</div>')}`,
    "Die Ausgabe ähnelt sich, weil PowerShell denselben zugrunde liegenden Befehl aufruft.",
    systemNote(
      "Aliase an sofort sichtbaren Beispielen einführen.",
      "Warum könnten dir und ls in PowerShell beide funktionieren?",
      "Sie sind alternative Namen für denselben Befehl.",
      "Get-Alias dir beziehungsweise Get-Alias ls zeigt die Zuordnung. Aliase erleichtern interaktive Eingabe und den Umstieg aus anderen Shells. In gemeinsam genutzten Skripten sind ausgeschriebene Cmdlet-Namen meist klarer.",
      "Ähnliche Ausgabe in verschiedenen Shells bedeutet nicht dieselbe interne Technik.",
      "Wie definieren wir Alias allgemein?",
      "1 und 2: Aliase. 3: Auflösung.",
      systemSources.aliases,
    ),
  ),
  S(
    "Alias · Grundbegriff",
    "Ein Spitzname für einen Befehl",
    `<div class="dictionary-equation"><div class="card"><small>Eingabe</small><code class="big-bits">dir</code></div><span class="math-sign">→</span>${book(
      "Alias-Tabelle",
      [
        ["dir", "Get-ChildItem"],
        ["ls", "Get-ChildItem"],
      ],
    )}<span class="math-sign">→</span><div class="meaning-result orange" style="font-size:2.6cqw">Get-ChildItem</div></div>${frag(1, '<div class="definition">Ein <em>Alias</em> ist ein alternativer Name für einen Befehl.</div>')}`,
    "PowerShell prüft Aliase vor Funktionen, Cmdlets und externen Programmen.",
    systemNote(
      "Alias mit dem etablierten Wörterbuchbild verbinden.",
      "Was steht nach der Namensauflösung tatsächlich fest?",
      "Welcher zugrunde liegende Befehl gemeint ist.",
      "Der Alias ist eine Zuordnung in PowerShell. Parameter lassen sich nicht beliebig in einem einfachen Alias fest verdrahten. Get-Command dir oder Get-Alias dir macht die Zuordnung sichtbar.",
      "Ein Alias ist keine Kopie des Programms und erzeugt keinen neuen Befehlscode.",
      "Warum kann dir in einer anderen Shell etwas anderes bedeuten?",
      "1: Definition.",
      systemSources.aliases,
    ),
  ),
  S(
    "Gleiche Eingabe · andere Shell",
    "dir sieht gleich aus, arbeitet aber anders",
    `<div class="grid two"><div>${codeCard("PowerShell", "dir  →  Alias für Get-ChildItem", "compact-code")}<p class="mini">Die Pipeline kann strukturierte Objekte erhalten.</p></div><div>${codeCard("cmd.exe", "dir  →  eingebauter cmd-Befehl", "compact-code")}<p class="mini">Die Ausgabe ist für die Textkonsole formatiert.</p></div></div>${answer(1, "Die Shell legt fest, wie ein Befehlsname interpretiert wird.", "Gleiche Buchstaben garantieren nicht dieselbe interne Umsetzung.")}`,
    "Darum ist es wichtig zu wissen, welche Shell gerade läuft.",
    systemNote(
      "Die Bedeutung eines Namens wieder an Kontext und Regeln knüpfen.",
      "Ist dir überall derselbe Befehl?",
      "Nein, PowerShell und cmd lösen ihn verschieden auf.",
      "PowerShell verwendet dir als Alias für Get-ChildItem. In cmd.exe ist dir ein interner Befehl. Beide listen typischerweise Verzeichnisinhalte, besitzen aber andere Optionen, Ausgabemodelle und Sprachregeln.",
      "Nicht von ähnlicher Oberfläche auf technische Gleichheit schließen.",
      "Neben eingebauten Befehlen kann PowerShell fremde Programme starten.",
      "1: Kernaussage.",
      systemSources.precedence,
    ),
  ),
  S(
    "Externe Programme",
    "Git gehört nicht zu PowerShell",
    `<div class="grid two"><div class="card"><p class="term">POWERSHELL</p><h3>erkennt den Namen</h3><code>git status</code><p>und startet die passende Datei.</p></div><div class="program-file">${icon("file")}<h3>git.exe</h3><p>Eigenständiges Programm mit eigenem Maschinencode.</p></div></div>${answer(1, "PowerShell kann Git starten. Git ist trotzdem ein separates Programm.")}`,
    "Argument status wird an Git weitergegeben.",
    systemNote(
      "Externe Programme von Cmdlets unterscheiden.",
      "Wer versteht hier das Wort status?",
      "Das gestartete Git-Programm.",
      "PowerShell erkennt git als externen Befehl und übergibt status als Argument. Windows startet git.exe als Prozess. Git wertet sein Argument aus und arbeitet mit dem aktuellen Repository.",
      "Nicht jeden Text hinter einem Befehl als PowerShell-Syntax erklären. Argumente gehören oft zum externen Programm.",
      "Wie findet PowerShell die Datei git.exe?",
      "1: Abgrenzung.",
      systemSources.precedence,
    ),
  ),
  S(
    "Externe Programme · Fundort",
    "Wo liegt git.exe?",
    `${terminalWindow("Get-Command git", "CommandType  Name     Source\nApplication  git.exe  C:\\Program Files\\Git\\cmd\\git.exe")}${frag(1, '<p class="mini">Der gezeigte Pfad ist ein Beispiel. Die tatsächliche Installation kann an einem anderen Ort liegen.</p>')}`,
    "Get-Command zeigt, welcher Befehl für einen Namen gewählt wird.",
    systemNote(
      "Die Auflösung eines externen Programms sichtbar machen.",
      "Was beweist die Spalte Source?",
      "Welche ausführbare Datei PowerShell gefunden hat.",
      "Get-Command sucht nach der PowerShell-Befehlsauflösung und zeigt Typ sowie Quelle. Bei einer Application steht dort der gefundene Dateipfad. Der Beispielpfad ist typisch, aber nicht garantiert.",
      "where ist in PowerShell selbst ein Alias; für das Windows-Programm müsste man where.exe schreiben.",
      "Müssten wir sonst jedes Mal den vollständigen Pfad tippen?",
      "1: Einschränkung zum Pfad.",
      systemSources.precedence,
    ),
  ),
  S(
    "PATH · das Problem",
    "Ein kompletter Dateipfad für jeden Start?",
    `${codeCard("Ohne Suchliste", '& "C:\\Program Files\\Git\\cmd\\git.exe" status')}${frag(1, '<div class="answer">Das ist eindeutig, aber lang und abhängig vom Installationsort.</div>')}${frag(2, '<p class="lead">Mit einer vereinbarten Suchliste reicht der kurze Name git.</p>')}`,
    "Die Shell braucht eine Liste von Ordnern, in denen sie nach Programmen suchen darf.",
    systemNote(
      "PATH aus dem praktischen Problem langer Programmpfade ableiten.",
      "Wie könnte PowerShell den Installationsort automatisch finden?",
      "In bekannten Ordnern nach dem Namen suchen.",
      "Ein vollständiger Pfad wählt die Datei direkt. Der Aufrufoperator & führt den in Anführungszeichen stehenden Pfad aus. Für alltägliche Aufrufe verwendet das System die PATH-Umgebungsvariable als Suchliste.",
      "PATH ist keine Liste aller installierten Programme und lädt Programme nicht automatisch.",
      "Wie sieht diese Suchliste aus?",
      "1: Problem. 2: Suchidee.",
      systemSources.path,
    ),
  ),
  S(
    "PATH · Suchliste für Programme",
    "Ordner werden der Reihe nach geprüft",
    `<div class="path-list"><div><span>1</span><code>C:\\Windows\\System32</code></div><div><span>2</span><code>C:\\Program Files\\PowerShell\\7</code></div><div class="hit"><span>3</span><code>C:\\Program Files\\Git\\cmd</code><b>git.exe gefunden</b></div><div><span>4</span><code>C:\\Tools</code></div></div>${frag(1, '<div class="definition"><em>PATH</em> ist eine geordnete Liste von Ordnern, in denen nach ausführbaren Programmen gesucht wird.</div>')}`,
    "Der erste passende Fund gewinnt.",
    systemNote(
      "PATH als geordnete Liste und nicht als magischen Ort erklären.",
      "Warum ist die Reihenfolge wichtig?",
      "Der erste passende Name bestimmt, welche Datei gestartet wird.",
      "Unter Windows trennt ein Semikolon die Ordner in PATH. PowerShell berücksichtigt zusätzlich seine eigene Befehlsrangfolge. Bei externen Programmen wird die erste passende ausführbare Datei in der Suchreihenfolge verwendet.",
      "Ein Ordner in PATH macht nicht jede beliebige Datei darin zu einem Cmdlet.",
      "Verfolgen wir git status nun vollständig bis zum Prozess.",
      "1: Definition.",
      systemSources.path,
    ),
  ),
  S(
    "Befehlsauflösung · git",
    "Vom Namen zum neuen Prozess",
    `<div class="command-route"><div><code>git status</code><small>Eingabe</small></div>${frag(1, "PowerShell<small>Befehlsarten prüfen</small>", "route-step")}${frag(2, "PATH<small>Ordner durchsuchen</small>", "route-step")}${frag(3, "git.exe<small>Datei gefunden</small>", "route-step")}${frag(4, "Windows<small>Prozess starten</small>", "route-step")}</div>`,
    "Git verarbeitet anschließend das Argument status.",
    systemNote(
      "Befehlsauflösung, PATH und Prozessstart verbinden.",
      "An welcher Stelle entsteht der Prozess?",
      "Nachdem PowerShell die Datei gefunden und Windows den Start angefordert hat.",
      "PowerShell prüft zuerst höher priorisierte Befehlsarten. Wird kein Alias, keine Funktion und kein Cmdlet namens git gewählt, sucht es nach externen Befehlen. Nach dem Fund startet Windows einen Prozess und übergibt status als Argument.",
      "PATH selbst startet nichts; es hilft beim Finden.",
      "Was könnte fehlen, wenn ein installiertes Programm nicht gefunden wird?",
      "1 bis 4: Auflösung bis zum Prozess.",
      systemSources.precedence,
    ),
  ),
  S(
    "Denkpause · Nicht gefunden",
    "Python ist installiert, aber python funktioniert nicht",
    `<div class="choices"><button class="choice" data-choice><b>A</b>Die CPU kann grundsätzlich kein Python ausführen.</button><button class="choice" data-choice><b>B</b>Der Installationsordner fehlt möglicherweise in PATH oder ein anderer Befehlsname ist vorgesehen.</button><button class="choice" data-choice><b>C</b>Das Terminalfenster kann keine Buchstaben anzeigen.</button></div>${answer(1, "B · Installation und Auffindbarkeit sind zwei verschiedene Fragen.", "Get-Command python prüft, ob PowerShell den Namen auflösen kann.")}`,
    "Auch py, python3 oder ein vollständiger Pfad können je nach Installation relevant sein.",
    systemNote(
      "Eine häufige PATH-Fehlersituation diagnostisch einordnen.",
      "Was wissen wir nach der Meldung Befehl nicht gefunden sicher?",
      "Nur, dass die Shell den eingegebenen Namen nicht auflösen konnte.",
      "Das Programm kann fehlen, anders heißen oder außerhalb der Suchpfade liegen. Unter Windows installiert der Python Launcher häufig den Befehl py. Get-Command python und Get-Command py helfen bei der Prüfung.",
      "Nicht sofort neu installieren; zuerst Namen und Fundort prüfen.",
      "Wo arbeitet ein gestartetes Programm relativ zu Dateien?",
      "Auswählen, begründen, dann 1: Auflösung.",
      systemSources.precedence,
    ),
  ),
  S(
    "Aktuelles Verzeichnis",
    "Wo befinden wir uns gerade?",
    `${terminalWindow("Get-Location", "Path\n----\nC:\\Users\\Mira\\Projekt")}${frag(1, '<div class="definition">Die Shell besitzt einen <em>aktuellen Arbeitsort</em>, auf den sich relative Pfade beziehen.</div>')}`,
    "Set-Location wechselt den Arbeitsort. cd ist dafür ein Alias.",
    systemNote(
      "Das aktuelle Verzeichnis aus einem sichtbaren Befehl ableiten.",
      "Warum kann dieselbe Eingabe .\\test.py an zwei Orten unterschiedliche Dateien meinen?",
      "Weil der relative Pfad vom aktuellen Arbeitsort beginnt.",
      "Get-Location zeigt den aktuellen PowerShell-Ort. Für Dateipfade entspricht er meist einem Ordner. PowerShell kann über Provider auch andere Orte darstellen; diese Erweiterung bleibt hier ausgeblendet.",
      "Das aktuelle Verzeichnis nicht mit dem Installationsordner von PowerShell verwechseln.",
      "Wie unterscheiden sich vollständige und relative Wegbeschreibungen?",
      "1: Definition.",
    ),
  ),
  S(
    "Pfade · Wegbeschreibungen",
    "Absolute Adresse oder Weg vom aktuellen Ort",
    `<div class="path-map"><div class="map-root">C:\\</div><div class="map-road"><span>Users</span><span>Mira</span><span class="current">Projekt</span><span>daten</span><strong>werte.csv</strong></div></div>${frag(1, '<div class="grid two"><div class="card"><h3>Absolut</h3><code>C:\\Users\\Mira\\Projekt\\daten\\werte.csv</code><p>Beginnt an einem festen Ausgangspunkt.</p></div><div class="card"><h3>Relativ</h3><code>.\\daten\\werte.csv</code><p>Beginnt im aktuellen Verzeichnis.</p></div></div>')}`,
    "Der Punkt steht hier für den aktuellen Ort.",
    systemNote(
      "Absolute und relative Pfade mit einer Stadtplananalogie unterscheiden.",
      "Welche Wegbeschreibung funktioniert unabhängig vom aktuellen Verzeichnis?",
      "Der absolute Pfad.",
      "Ein absoluter Windows-Pfad beginnt meist mit Laufwerksbuchstabe und Wurzel. Ein relativer Pfad wird vom aktuellen Ort aus aufgelöst. . bezeichnet diesen Ort ausdrücklich. PowerShell akzeptiert in vielen Fällen auch Schrägstriche, wir verwenden hier die übliche Windows-Schreibweise.",
      "Relativ bedeutet nicht ungenau; der Ausgangspunkt muss nur bekannt sein.",
      "Wie gelangen wir zum übergeordneten Ordner?",
      "1: Beide Beschreibungen.",
    ),
  ),
  S(
    "Pfade · eine Ebene nach oben",
    "Was bedeutet ..?",
    `<div class="folder-climb"><div><code>C:\\Users\\Mira\\Projekt</code><span>aktueller Ort</span></div><strong>↑ <code>..</code></strong><div><code>C:\\Users\\Mira</code><span>übergeordneter Ordner</span></div></div>${frag(1, terminalWindow("Set-Location ..\nGet-Location", "Path\n----\nC:\\Users\\Mira"))}`,
    ".. ist eine relative Angabe für den übergeordneten Ort.",
    systemNote(
      "Die häufige Pfadangabe .. konkret zeigen.",
      "Von welchem Teil des Pfades entfernen wir uns?",
      "Vom letzten Ordner Projekt.",
      "Set-Location .. wechselt vom aktuellen Ordner zum Elternordner. Mehrere Teile lassen sich kombinieren, etwa ..\\.. . Der Befehl cd .. ist durch den Alias cd ebenfalls üblich.",
      "Zwei Punkte sind kein spezieller PowerShell-Befehl; sie bilden einen Pfadbestandteil.",
      "Wie gelangen Daten zwischen Programmen und Terminal?",
      "1: Befehlsbeispiel.",
    ),
  ),
  S(
    "Programme und Datenströme",
    "Programme brauchen Ein- und Ausgänge",
    `<div class="stream-machine"><div class="stream-in">Eingabe<span>→</span></div><div class="machine-box"><strong>Programm</strong><small>verarbeitet Daten</small></div><div class="stream-outs"><div><span>→</span> normale Ausgabe</div><div><span>→</span> Fehlermeldung</div></div></div>`,
    "Viele Kommandozeilenprogramme verwenden dafür standardisierte Kanäle.",
    systemNote(
      "Standardkanäle über das Maschinenbild vorbereiten.",
      "Warum ist ein eigener Fehlerkanal nützlich?",
      "Normale Ergebnisse und Probleme lassen sich getrennt behandeln.",
      "Betriebssysteme stellen Prozessen standardmäßig Eingabe, normale Ausgabe und Fehlerausgabe bereit. Beim Start können diese Kanäle mit Terminal, Dateien oder anderen Programmen verbunden werden.",
      "Nicht jede grafische Anwendung benutzt diese Kanäle sichtbar.",
      "Wie heißen die drei klassischen Kanäle?",
    ),
  ),
  S(
    "Drei Standardkanäle",
    "stdin, stdout und stderr",
    `<div class="grid three streams"><div class="card"><code>stdin</code><h3>Standardeingabe</h3><p>Daten kommen in das Programm.</p></div><div class="card"><code>stdout</code><h3>Standardausgabe</h3><p>Normale Ergebnisse verlassen es.</p></div><div class="card error"><code>stderr</code><h3>Fehlerausgabe</h3><p>Probleme erhalten einen eigenen Kanal.</p></div></div>${frag(1, '<p class="mini">Bei einem Terminal sind Tastatur und sichtbare Textausgabe häufig mit diesen Kanälen verbunden.</p>')}`,
    "PowerShell besitzt zusätzlich weitere Ausgabeströme wie Warnung und Information.",
    systemNote(
      "Die drei klassischen Prozesskanäle benennen und PowerShell vorsichtig einordnen.",
      "Welcher Kanal ist für eine Fehlermeldung vorgesehen?",
      "stderr.",
      "stdin, stdout und stderr stammen aus der klassischen Prozessschnittstelle. PowerShell kennt einen Success- und Error-Stream sowie zusätzliche Streams. Für native Programme entsprechen Success und Error weitgehend stdout und stderr; die PowerShell-Pipeline ist jedoch nicht einfach stdin.",
      "PowerShell-Objektpipeline und klassischen stdin-Kanal nicht gleichsetzen.",
      "Was passiert, wenn wir eine Ausgabe mit > umleiten?",
      "1: Terminalbezug und PowerShell-Einschränkung.",
      systemSources.redirection,
    ),
  ),
  S(
    "Umleitung",
    "Ausgabe landet in einer Datei",
    `${terminalWindow("&quot;Hallo&quot; &gt; .\\test.txt", "")}${frag(1, '<div class="grid two"><div class="card"><h3>Ohne &gt;</h3><p>Die Erfolgsausgabe gelangt zum Host und erscheint normalerweise im Terminal.</p></div><div class="card"><h3>Mit &gt;</h3><p>PowerShell schreibt die Erfolgsausgabe in test.txt.</p></div></div>')}${answer(2, "Darum erscheint Hallo nicht zusätzlich als normale Ausgabe im Terminal.")}`,
    "> überschreibt die Zieldatei. >> hängt an eine bestehende Datei an.",
    systemNote(
      "Ausgabeumleitung an einem kleinen Beispiel sichtbar machen.",
      "Warum bleibt die sichtbare Ausgabezeile leer?",
      "Weil der Erfolgsstrom zur Datei umgeleitet wird.",
      "In PowerShell entspricht > für PowerShell-Ausgaben im Wesentlichen Out-File ohne Zusatzparameter. Die Datei entsteht im aktuellen Verzeichnis. Ein einzelnes > überschreibt vorhandenen Inhalt ohne Rückfrage, sofern das Schreiben erlaubt ist.",
      "Nicht sagen, das Terminal speichere den Text. PowerShell führt die Umleitung aus.",
      "Statt in eine Datei können Ergebnisse auch zum nächsten Befehl fließen.",
      "1: Vergleich. 2: Ergebnis.",
      systemSources.redirection,
    ),
  ),
  S(
    "Pipeline",
    "Ergebnis wird Eingabe für den nächsten Befehl",
    `<div class="pipeline-visual"><div><strong>Befehl A</strong><small>erzeugt Ergebnisse</small></div><span class="pipe-symbol">|</span><div><strong>Befehl B</strong><small>verarbeitet sie weiter</small></div></div>${frag(1, '<div class="definition">Eine <em>Pipeline</em> gibt Ergebnisse eines Befehls an einen weiteren Befehl weiter.</div>')}`,
    "Der senkrechte Strich | verbindet die Stationen.",
    systemNote(
      "Pipeline als Kombination kleiner Werkzeuge einführen.",
      "Welchen Vorteil hat die Weitergabe gegenüber einem riesigen Spezialbefehl?",
      "Kleine Schritte lassen sich flexibel kombinieren.",
      "Jeder Befehl übernimmt eine Aufgabe. Der Pipelineoperator verbindet die Ausgabe links mit der Verarbeitung rechts. Die Art der weitergegebenen Daten hängt von Shell und beteiligten Programmen ab.",
      "Eine Pipeline bedeutet nicht automatisch parallele Ausführung aller Schritte.",
      "Wie funktioniert das in einer klassischen Textpipeline?",
      "1: Definition.",
    ),
  ),
  S(
    "Textpipeline · klassisches Beispiel",
    "Nur Zeilen mit ERROR weitergeben",
    `${codeCard("Bash oder ähnliche Unix-Shell", "cat log.txt | grep ERROR")}${frag(1, '<div class="command-route three-step"><div>log.txt<small>gespeicherter Text</small></div><div>cat<small>gibt Zeilen aus</small></div><div>grep ERROR<small>filtert Textzeilen</small></div></div>')}${frag(2, '<div class="answer">Zwischen den Programmen fließt Text beziehungsweise ein Bytestrom.</div>')}`,
    "PowerShell kann ebenfalls externe Textprogramme verbinden. Bei Cmdlets nutzt es zusätzlich Objekte.",
    systemNote(
      "Eine klassische Textpipeline als Vergleichsbasis zeigen.",
      "Welche Information braucht grep, um zu filtern?",
      "Die Zeichenfolge ERROR in jeder Textzeile.",
      "cat liest die Datei und schreibt ihren Inhalt. grep liest diesen Strom und gibt passende Zeilen weiter. Unter Windows sind andere Werkzeuge üblich; die Folie erklärt das allgemeine Textprinzip, nicht einen PowerShell-Standardbefehl.",
      "cat ist hier ein externes Unix-Programm und nicht das PowerShell-Alias cat.",
      "Was macht PowerShell bei seinen eigenen Cmdlets anders?",
      "1: Ablauf. 2: Datenart.",
    ),
  ),
  S(
    "PowerShell-Pipeline",
    "Hinter der Tabelle stecken Objekte",
    `${terminalWindow("Get-Process", "Name        Id     CPU\n----        --     ---\nCode      4312   18,42\nexplorer  2104    7,15")}${frag(1, '<div class="answer">Die Anzeige ist Text. In der Pipeline liegen strukturierte Prozessobjekte.</div>')}`,
    "PowerShell formatiert Objekte erst für die sichtbare Ausgabe als Tabelle.",
    systemNote(
      "Den Unterschied zwischen sichtbarer Tabelle und internem Pipelinewert motivieren.",
      "Kann PowerShell die CPU-Zahl zuverlässig verwenden, ohne Textspalten zu zählen?",
      "Ja, weil CPU eine Eigenschaft des Objekts ist.",
      "Get-Process liefert Prozessobjekte. Das Formatierungssystem entscheidet später, welche Eigenschaften als Tabelle erscheinen. Die Beispielnamen und Werte sind illustrativ.",
      "Die Bildschirmtabelle nicht mit dem eigentlichen Objekt gleichsetzen.",
      "Was ist ein Objekt in diesem Zusammenhang?",
    ),
  ),
  S(
    "Objekt · strukturierte Information",
    "Eine Sache mit benannten Eigenschaften",
    `<div class="object-card"><span>PROCESS</span><dl><dt>Name</dt><dd>Code</dd><dt>Id</dt><dd>4312</dd><dt>CPU</dt><dd>18,42</dd><dt>WorkingSet</dt><dd>312 MB</dd></dl></div>${frag(1, '<div class="definition">Ein <em>Objekt</em> enthält strukturierte, zusammengehörige Informationen.</div>')}`,
    "Eigenschaften besitzen Namen. Dadurch können Befehle gezielt darauf zugreifen.",
    systemNote(
      "Objekte als benannte Struktur statt abstraktes Programmierkonzept erklären.",
      "Welche Eigenschaft könnten wir zum Sortieren verwenden?",
      "CPU, Id, Name oder Speicherverbrauch.",
      "Ein Prozessobjekt beschreibt einen bestimmten Prozess. Eigenschaften tragen Werte. Objekte können außerdem Methoden besitzen, also aufrufbare Aktionen. Für die ersten Pipelinebeispiele reichen Eigenschaften.",
      "Ein Objekt ist nicht die echte laufende Anwendung selbst, sondern eine strukturierte Repräsentation.",
      "Warum ist das besser als eine einzige Textzeile?",
      "1: Definition.",
      systemSources.member,
    ),
  ),
  S(
    "Text und Objekt",
    "Gleiche Information, andere Struktur",
    `<div class="grid two"><div>${codeCard("Textzeile", "Code 4312 18,42 312MB", "compact-code")}<p class="mini">Bedeutung entsteht aus Positionen und Trennzeichen.</p></div><div class="object-card compact"><span>OBJEKT</span><dl><dt>Name</dt><dd>Code</dd><dt>Id</dt><dd>4312</dd><dt>CPU</dt><dd>18,42</dd><dt>RAM</dt><dd>312 MB</dd></dl></div></div>${answer(1, "Beim Objekt kann PowerShell direkt nach der Eigenschaft CPU sortieren.", "Es muss dafür keine sichtbare Textspalte erraten.")}`,
    "Struktur macht Weiterverarbeitung zuverlässiger.",
    systemNote(
      "Text- und Objektverarbeitung vergleichbar gegenüberstellen.",
      "Was passiert bei der Textzeile, wenn ein Name Leerzeichen enthält?",
      "Die Spalten lassen sich schwerer zuverlässig erkennen.",
      "Text ist für Menschen gut lesbar, aber Programme brauchen Regeln zum Zerlegen. Objekte tragen die Feldnamen bereits. Bei der Ausgabe werden auch Objekte wieder als Text dargestellt.",
      "Objekte sind nicht grundsätzlich besser für jede Schnittstelle oder Datei.",
      "Nutzen wir die Eigenschaft CPU in einer Pipeline.",
      "1: Vorteil aufdecken.",
    ),
  ),
  S(
    "Pipeline mit Objekten",
    "Prozesse nach CPU-Zeit sortieren",
    `${codeCard("PowerShell", "Get-Process | Sort-Object CPU -Descending")}${frag(1, '<div class="pipeline-objects"><div>Prozessobjekte</div><span>|</span><div><strong>Sort-Object</strong><small>liest die Eigenschaft CPU</small></div><span>|</span><div>sortierte Objekte</div></div>')}${frag(2, '<div class="answer">Der zweite Befehl erhält dieselben strukturierten Objekte in neuer Reihenfolge.</div>')}`,
    "-Descending bedeutet: vom größten zum kleinsten Wert.",
    systemNote(
      "Objektpipeline an einer nützlichen Transformation erklären.",
      "Welche Information muss Sort-Object kennen?",
      "Den Eigenschaftsnamen CPU und die gewünschte Richtung.",
      "Get-Process erzeugt Objekte. Sort-Object liest deren CPU-Eigenschaft und ordnet die Objekte absteigend. Erst am Ende formatiert PowerShell sie für die Anzeige.",
      "CPU bezeichnet hier die bisher verbrauchte Prozessorzeit und nicht einfach die aktuelle Prozentlast.",
      "Können wir das Objektprinzip auf vertraute Dinge übertragen?",
      "1: Pipeline. 2: Ergebnisart.",
    ),
  ),
  S(
    "Denkpause · Eigenschaften",
    "Wonach lässt sich dieses Objekt sortieren?",
    `<div class="object-card person"><span>PERSON</span><dl><dt>Name</dt><dd>Anna</dd><dt>Alter</dt><dd>25</dd><dt>Ort</dt><dd>Nürnberg</dd></dl></div>${answer(1, "Nach Name, Alter oder Ort.", "Auf Prozesse übertragen: zum Beispiel Name, Id oder CPU.")}`,
    "Der Eigenschaftsname sagt dem nächsten Befehl, welchen Wert er verwenden soll.",
    systemNote(
      "Das Objektmodell ohne Computerfachwissen prüfen.",
      "Welche der drei Eigenschaften eignet sich für eine alphabetische Ortsliste?",
      "Ort.",
      "Das Personenobjekt ist ein didaktisches Beispiel. Sort-Object Ort würde mehrere solche Objekte nach ihrem Ortswert ordnen. Derselbe Mechanismus funktioniert mit Prozesseigenschaften.",
      "Nicht die sichtbare Reihenfolge der Eigenschaften mit der Sortierreihenfolge verwechseln.",
      "Wie finden wir heraus, welche Eigenschaften ein unbekanntes Objekt besitzt?",
      "1: Auflösung.",
    ),
  ),
  S(
    "Get-Member · Struktur entdecken",
    "Welche Eigenschaften besitzt ein Prozessobjekt?",
    `${codeCard("PowerShell", "Get-Process | Get-Member", "compact-code")}${frag(1, codeCard("gekürzte Ausgabe", "Name          MemberType\n----          ----------\nId            Property\nName          Property\nCPU           Property\nKill          Method", "compact-code"))}${frag(2, '<div class="answer">Get-Member zeigt Eigenschaften und Methoden der ankommenden Objekte.</div>')}`,
    "Die echte Liste ist deutlich länger. Die Folie zeigt nur einen Ausschnitt.",
    systemNote(
      "Get-Member als Werkzeug zur Selbsthilfe einführen.",
      "Welche Zeilen eignen sich direkt zum Sortieren?",
      "Die Eigenschaften, zum Beispiel CPU oder Name.",
      "Get-Member untersucht den Typ der Pipelineobjekte. Properties sind Datenfelder. Methods sind aufrufbare Aktionen. Die gekürzte Ausgabe dient nur der Orientierung.",
      "Eine Methode wie Kill nicht ohne Ziel und Wirkung ausprobieren.",
      "Verbinden wir nun alle bisher getrennten Stationen an git status.",
      "1: Ausgabe. 2: Bedeutung.",
      systemSources.member,
    ),
  ),
  S(
    "Alles zusammen · die große Kette",
    "Was passiert bei git status?",
    `<div class="big-system-chain"><div>Mensch<small>tippt</small></div><div>Windows Terminal<small>transportiert Text</small></div><div>PowerShell<small>löst git auf</small></div><div>PATH<small>findet git.exe</small></div><div>Windows<small>startet Prozess</small></div><div>CPU<small>führt Maschinencode aus</small></div><div>Git<small>liest den aktuellen Ordner</small></div><div>Terminal<small>zeigt Ausgabe</small></div></div>`,
    "Jede Station beantwortet eine andere Frage.",
    systemNote(
      "Das mentale Gesamtmodell in einer übersichtlichen Kette verdichten.",
      "Welche Station versteht status, und welche führt Maschinenanweisungen aus?",
      "Git versteht status; die CPU führt den Code aus.",
      "Das Terminal überträgt Eingabe an PowerShell. PowerShell findet Git. Windows startet dessen Prozess. Die CPU führt die geladenen Maschinenanweisungen aus. Git untersucht das Repository relativ zum aktuellen Verzeichnis und schreibt ein Ergebnis, das im Terminal erscheint.",
      "Die Kette ist logisch vereinfacht; Bibliotheken, Sicherheitsprüfungen und viele interne Schritte bleiben ausgeblendet.",
      "Gehen wir dieselbe Geschichte noch einmal langsam durch.",
    ),
  ),
  S(
    "git status · Schritt für Schritt",
    "Neun Stationen einer einzigen Eingabe",
    `<div class="story-steps"><div><b>1</b>Du tippst <code>git status</code>.</div>${frag(1, "<b>2</b>Das Terminal gibt den Text an PowerShell.", "story-step")}${frag(2, "<b>3</b>PowerShell erkennt Befehl und Argument.", "story-step")}${frag(3, "<b>4</b>Die Befehlsauflösung findet git.exe.", "story-step")}${frag(4, "<b>5</b>Windows startet einen Prozess.", "story-step")}${frag(5, "<b>6</b>Die CPU führt Maschinenanweisungen aus.", "story-step")}${frag(6, "<b>7</b>Git liest Dateien im aktuellen Repository.", "story-step")}${frag(7, "<b>8</b>Git schreibt sein Ergebnis.", "story-step")}${frag(8, "<b>9</b>Das Terminal zeigt es an.", "story-step")}</div>`,
    "Von der Eingabe bis zur Ausgabe greifen alle eingeführten Ebenen ineinander.",
    systemNote(
      "Die große Kette in erzählbare Einzelschritte zerlegen.",
      "An welcher Stelle würde ein falscher PATH-Eintrag auffallen?",
      "Beim Finden von git.exe, bevor der Prozess startet.",
      "Die Gruppe kann jeden Schritt mit dem passenden Begriff begründen. status ist ein Argument für Git. Git liest neben Dateien auch Metadaten seines Repositorys. Die genaue interne Git-Arbeit ist nicht Teil dieses Abschnitts.",
      "Nicht sagen, PowerShell führe den Git-Maschinencode selbst aus.",
      "Jetzt baut die Gruppe eine ähnliche Kette selbst.",
      "1 bis 8: Je einen weiteren Schritt aufdecken.",
    ),
  ),
  S(
    "Abschlussübung · die Kette bauen",
    "Was passiert bei python test.py?",
    `<div class="sort-pool wide"><span>CPU</span><span>Shell</span><span>Terminal</span><span>PATH</span><span>Programmdatei</span><span>Betriebssystem</span><span>Tastatur</span><span>Prozess</span></div>${frag(1, '<div class="answer">Eine mögliche Erzählung:<small>Tastatur → Terminal → Shell → PATH findet Python → Betriebssystem startet einen Prozess → Python verarbeitet test.py → CPU führt Maschinenanweisungen aus → Ausgabe zurück zum Terminal.</small></div>')}`,
    "Entscheidend ist die begründete Geschichte, nicht eine einzige perfekte Kartenreihenfolge.",
    systemNote(
      "Die Teilnehmenden das Gesamtmodell selbst rekonstruieren lassen.",
      "Welche Karte hilft beim Finden von Python, welche beim tatsächlichen Ausführen?",
      "PATH hilft beim Finden; Betriebssystem und CPU ermöglichen die Ausführung.",
      "Die Auflösung ist eine sinnvolle vereinfachte Geschichte. Die Programmdatei test.py wird durch das Python-Programm verarbeitet. Je nach Installation kann der Startbefehl py oder python3 heißen.",
      "test.py nicht als direkt von der CPU verstandene Programmdatei darstellen.",
      "Zum Schluss erklären wir die Kernbegriffe ohne Folientext.",
      "1: Mögliche Geschichte erst nach der Gruppenarbeit.",
    ),
  ),
  S(
    "Blitzrunde · in eigenen Worten",
    "Kannst du den Begriff in einem Satz erklären?",
    `<div class="term-cloud"><span>Computer</span><span>Programm</span><span>CPU</span><span>Maschinencode</span><span>Assembly</span><span>Compiler</span><span>Betriebssystem</span><span>Prozess</span><span>Terminal</span><span>Shell</span><span>PATH</span><span>Pipeline</span></div>${frag(1, '<div class="answer">Regel: kein Begriff darf mit genau demselben Begriff erklärt werden.</div>')}`,
    "Erklärt es so, wie ihr es jemandem zuhause erzählen würdet.",
    systemNote(
      "Aktives Erklären statt Wiedererkennen prüfen.",
      "Welche zwei Begriffe werden am leichtesten verwechselt?",
      "Oft Programm und Prozess sowie Terminal und Shell.",
      "Begriffe reihum verteilen. Kurze alltagstaugliche Erklärungen genügen. Bei Unklarheit nach einem konkreten Beispiel fragen, statt sofort die Musterdefinition vorzulesen.",
      "Keine wortgetreue Formulierung als einzig richtige Antwort verlangen.",
      "Die Abschlussfolie verbindet die gesamte Geschichte noch einmal.",
      "1: Erklärregel.",
    ),
  ),
  S(
    "Abschluss · vom Menschen zur Hardware",
    "Viele Schichten, eine ausgeführte Handlung",
    `<div class="final-system-stack"><div>Menschliche Absicht</div><div>Programmiersprache oder Shell-Befehl</div><div>Übersetzer oder Shell</div><div>Betriebssystem und Prozess</div><div>Maschinenanweisungen</div><div>CPU und elektronische Zustände</div></div>${frag(1, '<div class="answer">Jede Schicht macht die darunterliegende Komplexität einfacher nutzbar.<small>Die unteren Schichten verschwinden nicht. Wir können sie gezielt wieder sichtbar machen.</small></div>')}`,
    "Damit reicht unsere Kette von der Idee bis zur physischen Ausführung.",
    systemNote(
      "Das Seminar mit dem durchgehenden Abstraktionsgedanken schließen.",
      "Welche Schicht würdet ihr bei einem Befehl nicht gefunden zuerst prüfen?",
      "Shellauflösung, PATH und aktuelles Verzeichnis.",
      "Die Abschlussfolie ist eine Ebenenübersicht und keine exakte Zeitachse. Je nach Handlung können weitere Bibliotheken, Dienste, Treiber und Netzwerkkomponenten beteiligt sein. Das mentale Modell hilft, Fragen an der passenden Ebene zu stellen.",
      "Nicht aus der vereinfachten Reihenfolge auf einen einzigen universellen Ausführungspfad schließen.",
      "Optional folgen Architektur sowie Java und Bytecode als Exkurse.",
      "1: Abschlussgedanke.",
    ),
  ),
];

const javaExcursion = [
  S(
    "Optionaler Exkurs · Java und Bytecode",
    "Java fügt eine portable Zwischenform ein",
    `<div class="translation-chain java-chain"><div class="node">Java-Quellcode<pre>int x = 5 + 3;</pre></div><span class="arrow">→</span><div class="node accent">Java-Compiler<br><small>javac</small></div><span class="arrow">→</span><div class="node">Bytecode<br><small>.class-Datei</small></div><span class="arrow">→</span><div class="node accent">Java Virtual Machine</div><span class="arrow">→</span><div class="node">Maschinenanweisungen</div></div>${frag(1, '<div class="answer">Bytecode ist für die Java Virtual Machine gedacht, nicht direkt für x86-64 oder AArch64.</div>')}`,
    "Dieser Exkurs ergänzt das Grundmodell. Der Hauptpfad funktioniert ohne ihn.",
    systemNote(
      "Java-Bytecode als optionale Zwischenform korrekt einordnen.",
      "Welche Station ist hier zusätzlich zu unserem vereinfachten Pythonbild sichtbar?",
      "Bytecode und die Java Virtual Machine.",
      "javac übersetzt Java-Quellcode in Java-Bytecode. Eine JVM lädt und prüft diesen Code und kann ihn interpretieren oder häufig ausgeführte Teile zur Laufzeit in nativen Maschinencode übersetzen. Die CPU führt am Ende wieder Maschinenanweisungen aus.",
      "Bytecode nicht mit dem Maschinencode der physischen CPU gleichsetzen.",
      "Warum lohnt sich diese zusätzliche Ebene?",
      "1: Bytecode-Abgrenzung.",
      "Oracle Java-Dokumentation: https://docs.oracle.com/javase/specs/jvms/se25/html/",
    ),
  ),
  S(
    "Optionaler Exkurs · Java und Bytecode",
    "Dieselbe class-Datei, passende JVM",
    `<div class="bytecode-platforms"><div class="bytecode-file">Java-Bytecode<br><code>Rechnung.class</code></div><span>↙</span><span>↓</span><span>↘</span><div>JVM für Windows<br><small>x86-64</small></div><div>JVM für macOS<br><small>Apple Silicon</small></div><div>JVM für Linux<br><small>AArch64</small></div></div>${frag(1, '<div class="answer">Die Bytecode-Ebene erleichtert Portabilität.<small>Für jede Plattform braucht es eine passende JVM und passende Bibliotheken.</small></div>')}`,
    "Portabel bedeutet nicht automatisch ohne jede Plattformabhängigkeit.",
    systemNote(
      "Den Zweck von Bytecode über mehrere Zielplattformen erklären.",
      "Was muss sich zwischen den drei Computern unterscheiden?",
      "Die JVM-Umsetzung für Betriebssystem und CPU-Architektur.",
      "Eine kompatible class-Datei kann auf verschiedenen JVM-Implementierungen laufen. Die JVM übersetzt oder interpretiert Bytecode passend zur Plattform. Native Bibliotheken, Versionen und Systemzugriffe können die Portabilität begrenzen.",
      "Write once, run anywhere nicht als absolute Garantie für jede Umgebung darstellen.",
      "Vom Exkurs geht es zurück zur Abschlussübersicht.",
      "1: Kernaussage und Einschränkung.",
      "Oracle Java-Dokumentation: https://docs.oracle.com/javase/specs/jvms/se25/html/",
    ),
  ),
];

// Die bisherigen Architekturfolien bleiben Exkurs. Der neue Hauptteil kommt davor.
const firstArchitectureIndex = slides.indexOf(architectures[0]);
const previousMainSlides = slides.slice(0, firstArchitectureIndex);
previousMainSlides[previousMainSlides.length - 1].bottom =
  "Vereinfachtes Übersetzungsmodell · Die Bits entsprechen exakt den gezeigten Assembly-Anweisungen.";
for (const slide of architectures)
  slide.bottom = slide.bottom.replace(/ <a class="deck-link".*?<\/a>/g, "");

slides.splice(
  0,
  slides.length,
  ...previousMainSlides,
  ...systemSlides,
  ...architectures,
  ...javaExcursion,
);

const systemMainEnd = slides.indexOf(systemSlides[systemSlides.length - 1]);
const architectureStart = slides.indexOf(architectures[0]);
const javaStart = slides.indexOf(javaExcursion[0]);
slides[systemMainEnd].bottom +=
  ` <a class="deck-link" href="#${architectureStart + 1}/0">Architektur-Exkurs</a>` +
  ` <a class="deck-link" href="#${javaStart + 1}/0">Java-Exkurs</a>`;
for (const slide of [...architectures, ...javaExcursion])
  slide.bottom += ` <a class="deck-link" href="#${systemMainEnd + 1}/1">← Zum Abschluss</a>`;

slides[0].lead = "Von Bits, Python und Betriebssystem bis zur PowerShell";
