"use strict";
// Alle Inhalte liegen lokal vor. Kein Fetch, keine Bibliotheken, keine Speicherung.
const paths = {
  person:
    '<circle cx="48" cy="28" r="12"/><path d="M24 80v-12a24 24 0 0 1 48 0v12M36 80V65m24 15V65"/>',
  desktop:
    '<rect x="10" y="16" width="76" height="49" rx="5"/><path d="M48 65v15M30 82h36M18 56h60"/>',
  phone:
    '<rect x="27" y="8" width="42" height="80" rx="8"/><path d="M40 17h16M42 78h12"/>',
  game: '<path d="M29 28h38c14 0 22 41 14 46-7 5-17-12-23-12H38c-6 0-16 17-23 12-8-5 0-46 14-46Z"/><path d="M30 38v20M20 48h20M63 41v1M73 50v1"/>',
  car: '<path d="m17 43 9-22h44l9 22M13 45h70v26H13ZM22 71v9m52-9v9M23 54h12m26 0h12"/>',
  washer:
    '<rect x="18" y="8" width="60" height="80" rx="5"/><path d="M18 28h60M28 18h13m23 0h4"/><circle cx="48" cy="56" r="19"/><path d="M30 58q9-10 18 0t18 0"/>',
  calc: '<rect x="22" y="8" width="52" height="80" rx="5"/><path d="M31 18h34v17H31ZM32 47h4m10 0h4m10 0h4M32 59h4m10 0h4m10 0h4M32 71h4m10 0h4m10 0h4"/>',
  cpu: '<rect x="23" y="23" width="50" height="50" rx="6"/><rect x="33" y="33" width="30" height="30" rx="3"/><path d="M33 10v13m15-13v13m15-13v13M33 73v13m15-13v13m15-13v13M10 33h13M10 48h13M10 63h13M73 33h13M73 48h13M73 63h13"/>',
  file: '<path d="M25 9h31l17 17v61H25ZM55 9v19h18M35 43h28M35 54h28M35 65h19"/>',
  ram: '<rect x="8" y="25" width="80" height="45" rx="3"/><path d="M20 70v10m14-10v10m14-10v10m14-10v10m14-10v10M18 36h13v21H18ZM41 36h13v21H41ZM64 36h13v21H64Z"/>',
  drive:
    '<rect x="16" y="13" width="64" height="71" rx="6"/><circle cx="48" cy="43" r="19"/><circle cx="48" cy="43" r="5"/><path d="m49 45 20 22M26 75h7m7 0h7"/>',
};
const icon = (name, cls = "icon") =>
  `<svg class="${cls}" viewBox="0 0 96 96" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
const frag = (n, html, cls = "") =>
  `<div class="fragment ${cls}" data-step="${n}">${html}</div>`;
const answer = (n, html, small = "") =>
  frag(n, `${html}${small ? `<small>${small}</small>` : ""}`, "answer");
const model = "";
const field = (op = "0010", value = "00000011", labels = true) =>
  `<div class="instruction"><div class="field operation"><code>${op}</code>${labels ? '<div class="meaning">Addieren<small>Was tun?</small></div>' : ""}</div><div class="field value"><code>${value}</code>${labels ? '<div class="meaning">3<small>Mit welchem Wert?</small></div>' : ""}</div></div>`;
const bitBoard = (id, value) =>
  `<div class="bit-board" data-board="${id}"><div class="bit-row">${[128, 64, 32, 16, 8, 4, 2, 1].map((w) => `<div class="bit-column"><span class="weight">${w}</span><button class="bit" data-weight="${w}" aria-label="Stellenwert ${w}" aria-pressed="${!!(value & w)}">${value & w ? 1 : 0}</button></div>`).join("")}</div><div class="sum" aria-live="polite"></div></div>`;
const note = (
  goal,
  question,
  expected,
  explain,
  misconception,
  transition,
  steps,
  source = "",
) => ({
  goal,
  question,
  expected,
  explain,
  misconception,
  transition,
  steps,
  source,
});
const slides = [
  {
    chapter: "Die Leitfrage",
    title: "Was passiert zwischen Eingabe und Ergebnis?",
    eyebrow: "01 · Eine Reise ins Innere",
    class: "hero",
    heading: "Du gibst etwas ein.<br><em>Was passiert dann?</em>",
    lead: "Vom Gedanken zum Opcode",
    html: `<div class="hero-art">${icon("cpu", "")}</div><div class="hero-caption">5 + 3 → ? → 8</div><div class="flow"><div class="node">Mensch</div><span class="arrow">→</span><div class="node unknown">?</div><span class="arrow">→</span><div class="node unknown">?</div><span class="arrow">→</span><div class="node unknown">?</div><span class="arrow">→</span><div class="node accent">Hardware</div></div>`,
    bottom: "Welche Stationen vermutet ihr dazwischen?",
    notes: note(
      "Eine gemeinsame Leitfrage öffnen.",
      "Was passiert zwischen eurer Eingabe und dem Ergebnis?",
      "Tastatur, Strom, Rechnen, Apps, vielleicht Internet.",
      "Erst sammeln, nichts vorschnell korrigieren. Hardware bedeutet die anfassbaren Teile. Wir verfolgen heute eine einzige Rechnung: 5 + 3. Der Abschnitt reicht bis zum Aufbau einer Maschinenanweisung; die übrigen Stationen bleiben bewusst offen. Etwa 30–40 Minuten mit Diskussion, je nach Lerngruppe.",
      "Nicht jede Berechnung braucht das Internet. Die offenen Kästen sind noch keine vollständige technische Kette.",
      "Bevor wir hineinschauen: Was zählt überhaupt als Computer?",
      "Ohne Einblendung. Erst die Frage wirken lassen.",
    ),
  },
  {
    chapter: "Computer",
    title: "Wo steckt ein Computer?",
    eyebrow: "Mitdenken · Handzeichen",
    heading: "Wo steckt ein Computer?",
    lead: "PC, Alltagsgerät oder beides?",
    html: `<div class="grid device-grid">${[
      ["desktop", "Desktop-PC", "ist ein Computer"],
      ["phone", "Smartphone", "ist ein Computer"],
      ["game", "Spielekonsole", "ist ein Computer"],
      ["car", "Modernes Auto", "enthält mehrere Computer"],
      [
        "washer",
        "Moderne Waschmaschine",
        "enthält eine Steuerung mit Computer",
      ],
      ["calc", "Taschenrechner", "ist ein einfacher Computer"],
    ]
      .map(
        ([i, t, a]) =>
          `<div class="card device">${icon(i)}<div><h3>${t}</h3>${frag(1, `<p>${a}</p>`)}</div></div>`,
      )
      .join("")}</div>`,
    bottom: "Ein Bildschirm und eine Tastatur sind keine Voraussetzung.",
    notes: note(
      "Den Begriff vom Desktop-PC lösen.",
      "Bei welchen Geräten würdet ihr die Hand heben?",
      "Meist PC und Handy, Unsicherheit bei Waschmaschine und Auto.",
      "Geräte einzeln abfragen. Bei Auto und Waschmaschine sind moderne, elektronisch gesteuerte Modelle gemeint. Das ganze Auto ist nicht ein einzelner Computer; es enthält mehrere.",
      "Nicht jedes historische oder rein mechanische Haushaltsgerät enthält einen Computer.",
      "Welche gemeinsame Fähigkeit haben diese Geräte?",
      "1: Alle Zuordnungen einblenden; Grenzfälle gemeinsam besprechen.",
    ),
  },
  {
    chapter: "Computer",
    title: "Was wird verarbeitet?",
    eyebrow: "Ein konkretes Beispiel",
    heading: "Die Wäsche soll auf 40 °C",
    lead: "Was muss die Maschine dafür wissen – und tun?",
    html: `<div class="grid three"><div class="card"><small>Gemessen</small><strong class="big blue">20 °C</strong>${frag(1, "<h3>Daten</h3><p>Informationen, zum Beispiel eine gemessene Temperatur.</p>")}</div>${frag(2, '<small>Vorgegeben</small><strong class="big orange">Heizen</strong><h3>Anweisung</h3><p>Ist es kälter als 40 °C? Dann heizen.</p>', "card")}${frag(3, '<small>Ausgelöst</small><strong class="big mint">Wärme</strong><h3>Ergebnis</h3><p>Die Steuerung schaltet die Heizung ein.</p>', "card")}</div>`,
    bottom:
      "Daten beschreiben etwas. Anweisungen legen fest, was damit passiert.",
    notes: note(
      "Daten und Anweisungen getrennt aus einem Alltagsszenario ableiten.",
      "Reicht die gemessene Zahl 20 allein, um zu wissen, was die Maschine tun soll?",
      "Nein, wir brauchen eine Zieltemperatur und eine Regel.",
      "Zuerst den Messwert benennen. Daten können Zahlen, Texte, Bilder oder Messwerte sein. Danach eine Regel hinzufügen. Die Regel wird geprüft, die Heizung angesteuert. Regelkreise und Sicherheitsabschaltungen sind hier ausgeblendet.",
      "Die Zahl 20 ist noch keine Anweisung. Die Regel in deutscher Sprache ist unsere Beschreibung, kein direkt ausführbarer CPU-Befehl.",
      "Diese gemeinsame Fähigkeit können wir jetzt in einem Satz festhalten.",
      "1: Daten benennen. 2: Regel und Anweisung. 3: Ergebnis.",
    ),
  },
  {
    chapter: "Computer",
    title: "Ein Computer verarbeitet Daten",
    eyebrow: "Jetzt hat es einen Namen",
    heading: "Was ist ein Computer?",
    html: `<div class="definition">Ein Computer ist eine <span class="blue">Maschine</span>, die <span class="blue">Daten</span> verarbeitet, indem sie <span class="orange">Anweisungen</span> ausführt.</div>${frag(1, '<div class="flow"><div class="node">Daten</div><span class="arrow">→</span><div class="node accent">Verarbeitung<br><small>nach Anweisungen</small></div><span class="arrow">→</span><div class="node">Ergebnis</div></div>')}`,
    bottom: "Welche Daten verarbeitet ein Taschenrechner?",
    notes: note(
      "Eine kurze Definition aus dem Beispiel ableiten.",
      "Wie würdet ihr die gemeinsame Fähigkeit aller Geräte beschreiben?",
      "Eingaben verarbeiten, rechnen, Regeln befolgen, etwas ausgeben.",
      "Die Definition einzeln lesen: Maschine = physisches Gerät; Daten = dargestellte Informationen; Anweisungen = festgelegte Verarbeitungsschritte. Beim Taschenrechner sind 5 und 3 Daten, das Addieren ist die Operation.",
      "Computer verarbeiten nicht nur Zahlen im alltäglichen Sinn; auch Text und Bilder werden intern codiert.",
      "Wir bleiben bei der kleinsten greifbaren Aufgabe: 5 + 3.",
      "1: Die gemeinsame Verarbeitungskette zeigen.",
    ),
  },
  {
    chapter: "Programm",
    title: "Eine Idee wird zu Schritten",
    eyebrow: "Unser durchgehendes Beispiel",
    heading: "Wie wird aus 5 + 3 ein Ablauf?",
    html: `<div class="equation"><span class="blue">5</span><span class="operator">+</span><span class="blue">3</span><span class="operator">=</span><span class="soft">?</span></div><div class="grid four sequence">${frag(1, "<h3>5 bereitstellen</h3>", "card")}${frag(2, "<h3>3 bereitstellen</h3>", "card")}${frag(3, "<h3>Addieren</h3>", "card")}${frag(4, "<h3>Ergebnis ablegen</h3>", "card")}</div>`,
    bottom:
      "Eine Aufgabe lässt sich als Folge genauer Anweisungen beschreiben.",
    notes: note(
      "Eine Folge von Anweisungen vor dem Begriff Programm zeigen.",
      "Welche einzelnen Arbeitsschritte stecken in dieser Rechnung?",
      "Zahlen merken, zusammenzählen, Ergebnis merken.",
      "Diese vier Schritte sind ein menschlicher Ablaufplan. Nicht behaupten, jede echte CPU oder jeder Compiler müsse exakt vier Befehle daraus machen. Noch keine Register oder Speicheradressen einführen.",
      "Ein Programm muss nicht immer eine sichtbare Oberfläche haben. Die vier Karten sind noch kein echter Maschinencode.",
      "Wie nennen wir eine ausführbare Folge von Anweisungen?",
      "1–4: Jeweils einen Schritt zeigen und kurz von der Gruppe begründen lassen.",
    ),
  },
  {
    chapter: "Programm",
    title: "Eine Folge von Anweisungen",
    eyebrow: "Der neue Begriff · Programm",
    heading: "Die Anweisungen bilden ein Programm",
    html: `<div class="definition">Ein <em>Programm</em> ist eine Folge von Anweisungen, die ein Computer ausführen kann.</div>${frag(1, '<div class="grid three"><div class="card"><h3>Eine kleine Rechnung</h3><p>Wenige Schritte für eine Aufgabe.</p></div><div class="card"><h3>Eine App</h3><p>Viele zusammengehörige Aufgaben.</p></div><div class="card"><h3>Eine Gerätesteuerung</h3><p>Arbeitet oft ohne sichtbares Fenster.</p></div></div>')}`,
    bottom: "Wer führt diese Anweisungen tatsächlich aus?",
    notes: note(
      "Programm als ausführbaren Ablauf verankern.",
      "Ist auch ein Ablauf ohne Fenster ein Programm?",
      "Ja, beispielsweise eine Steuerung oder eine kleine Berechnung.",
      "Nicht der Umfang oder das Fenster entscheidet. Programme können auch Verzweigungen und Wiederholungen enthalten; eine Folge ist daher nicht zwingend eine gerade Liste ohne Entscheidungen.",
      "Eine bloße deutsche Wunschbeschreibung ist noch kein ausführbares Programm.",
      "Wir brauchen in der Maschine einen Teil, der die Anweisungen ausführt.",
      "1: Drei Größenordnungen zeigen, ohne neue Fachbegriffe einzuführen.",
    ),
  },
  {
    chapter: "CPU",
    title: "Wer führt die Anweisungen aus?",
    eyebrow: "Im Inneren des Computers",
    heading: "Wer rechnet eigentlich?",
    html: `<div class="split"><div>${icon("cpu", "cpu-visual")}</div><div><p class="label">Der ausführende Baustein</p>${frag(1, '<span class="big-number orange">CPU</span><p class="mini">Central Processing Unit · zentraler Prozessor</p>')}${frag(2, '<p class="lead">Die CPU führt <span class="orange">Maschinenanweisungen</span> aus.</p><p class="mini">Das sind Anweisungen, die zu genau diesem Prozessor passen.</p>')}</div></div>`,
    bottom: "Wie gelangt ein gespeichertes Programm zur CPU?",
    notes: note(
      "CPU als ausführenden Baustein einführen.",
      "Welcher Teil im Computer führt die einzelnen Rechenschritte aus?",
      "Prozessor, Chip, vielleicht Festplatte.",
      "CPU zuerst als Name für den Prozessor vorstellen. Maschinenanweisungen sind die codierten Anweisungen, die die CPU ausführen kann. Andere Recheneinheiten gibt es auch; für dieses erste Modell verfolgen wir die CPU.",
      "Eine CPU denkt nicht über die Absicht eines Menschen nach. Die Zeichnung ist ein Symbol, kein maßstabsgetreuer Aufbau.",
      "Die CPU braucht Zugriff auf die Anweisungen. Wo liegen sie vorher?",
      "1: Name und ausgeschriebene Form. 2: Aufgabe der CPU.",
    ),
  },
  {
    chapter: "CPU",
    title: "Gespeichert ist noch nicht gestartet",
    eyebrow: "Der Weg zur Ausführung",
    heading: "Wo wartet ein Programm?",
    html: `<div class="flow"><div class="node">${icon("drive")}<strong>Speichergerät</strong><p class="mini">z. B. SSD<br>Programmdatei liegt bereit</p></div><span class="arrow fragment" data-step="1">→</span>${frag(1, `${icon("ram")}<strong>Arbeitsspeicher</strong><p class="mini">RAM<br>Benötigte Teile liegen bereit</p>`, "node")}<span class="arrow fragment" data-step="2">→</span>${frag(2, `${icon("cpu")}<strong>CPU</strong><p class="mini">führt Maschinenanweisungen aus</p>`, "node accent")}</div>${frag(3, '<p class="mini">Beim Start werden benötigte Teile in den Arbeitsspeicher geladen. Der Ablauf ist hier vereinfacht.</p>')}`,
    bottom:
      "Eine Programmdatei kann gespeichert sein, auch wenn sie gerade nicht läuft.",
    notes: note(
      "Gespeichertes Programm und Ausführung unterscheiden, ohne Prozess vorwegzunehmen.",
      "Rechnet ein Programm schon, nur weil seine Datei auf dem Computer liegt?",
      "Nein, es muss gestartet werden.",
      "Für einen gewöhnlichen PC erklären: Speichergerät hält die Datei dauerhaft; RAM ist der Arbeitsspeicher für gerade benötigte Inhalte; CPU führt die Anweisungen aus. RAM bedeutet Random Access Memory, SSD Solid State Drive; die Abkürzungen nur bei Nachfrage ausführen. Das Betriebssystem organisiert den Start, kommt aber erst später als Thema.",
      "Nicht das gesamte Programm muss sofort geladen werden. Caches, virtueller Speicher und Geräte mit direkter Ausführung aus anderem Speicher sind ausgeblendet. Pfeile bedeuten Bereitstellung von Code, nicht dass die CPU die Datei physisch erhält.",
      "Jetzt prüfen wir gemeinsam, ob gespeichert und ausgeführt auseinandergehalten werden.",
      "1: Arbeitsspeicher. 2: CPU. 3: Vereinfachung und Start erklären.",
    ),
  },
  {
    chapter: "Verständnischeck",
    title: "Rechnet ein gespeichertes Programm schon?",
    eyebrow: "Denkpause 01 · Entscheiden & begründen",
    heading: "Das Programm ist gespeichert.<br>Es wurde noch nicht gestartet.",
    lead: "Welche Aussage passt?",
    html: `<div class="choices"><button class="choice" data-choice><b>A</b>Die CPU führt es bereits aus.</button><button class="choice" data-choice><b>B</b>Die Anweisungen liegen bereit, werden aber noch nicht ausgeführt.</button></div>${answer(1, "B · Gespeichert sein reicht nicht.", "Zum Ausführen muss das Programm gestartet werden. Ein Fenster ist dafür keine Voraussetzung.")}`,
    bottom: "Erst abstimmen. Mit „Weiter“ die Erklärung einblenden.",
    notes: note(
      "Verständnis statt reines Begriffsabrufen prüfen.",
      "Was unterscheidet eine gespeicherte Programmdatei von ihrer Ausführung?",
      "B, weil der Start fehlt.",
      "Die Auswahl markiert nur die Vermutung; die Lösung kommt erst mit Weiter. Ein Programm kann nach dem Start ohne Fenster laufen. Das Beispiel setzt voraus, dass auch kein anderer Mechanismus es gestartet hat.",
      "Nicht aus einem unsichtbaren Fenster auf fehlende Ausführung schließen.",
      "Nun wissen wir, wer ausführt. Aber in welcher Form erhält die CPU die Anweisungen?",
      "1: Antwort mit Begründung. Bei A zur Speicherfolie zurückgehen.",
    ),
  },
  {
    chapter: "Bits",
    title: "Wie kommt eine Anweisung in die CPU?",
    eyebrow: "Die nächste offene Frage",
    heading: "„Rechne bitte 5 plus 3.“",
    lead: "Kann die CPU mit diesem Satz direkt etwas anfangen?",
    html: `<div class="split"><div class="card"><p class="label">Unsere Beschreibung</p><div class="equation"><span>5 + 3</span></div></div><div>${icon("cpu", "cpu-visual")}</div></div>${answer(1, "Die CPU braucht passend codierte Maschinenanweisungen.", "Wörter und Zeichen müssen erst durch andere Programme verarbeitet werden.")}`,
    bottom: "Wie lässt sich Information überhaupt elektronisch darstellen?",
    notes: note(
      "Die Lücke zwischen Absicht und maschinengeeigneter Codierung öffnen.",
      "Liest die CPU den deutschen Satz so, wie wir ihn lesen?",
      "Nein; sie braucht eine andere Darstellung, vielleicht Nullen und Einsen.",
      "Die CPU führt keine deutsche Bitte unmittelbar aus. Programme können Text als Daten bearbeiten und passende Aktionen auslösen. Den Übersetzungsweg noch nicht ausrollen.",
      "Auch bei Spracheingabe oder KI läuft Software. Die CPU versteht dadurch nicht direkt den Satz als Maschinenanweisung.",
      "Bevor Bits Befehle bedeuten können, brauchen wir zwei unterscheidbare Zustände.",
      "1: Auflösung nach der Diskussion.",
    ),
  },
  {
    chapter: "Bits",
    title: "Zwei zuverlässig unterscheidbare Zustände",
    eyebrow: "Elektronik → Darstellung",
    heading: "Warum ausgerechnet 0 und 1?",
    html: `<div class="signal-row"><div class="signal"><label>Niedriger Spannungsbereich</label><span class="digit fragment" data-step="1">0</span><span class="wave"></span></div><div class="signal high"><label>Hoher Spannungsbereich</label><span class="digit fragment" data-step="1">1</span><span class="wave"></span></div></div>${frag(2, '<p class="lead">Zwei logische Zustände. Wir schreiben dafür <span class="blue">0</span> und <span class="orange">1</span>.</p><p class="mini">Vereinfacht: Spannungsbereiche, keine Aussage „kein Strom / Strom“.</p>')}`,
    bottom: "Die Ziffern sind unsere Darstellung der Zustände.",
    notes: note(
      "Binäre Darstellung sauber aus elektrischen Signalzuständen motivieren.",
      "Warum könnten zwei klar unterscheidbare Zustände praktisch sein?",
      "Einfach auseinanderzuhalten; an/aus als Alltagsvergleich.",
      "Digitale Schaltungen unterscheiden Spannungsbereiche. In der hier verwendeten positiven Logik steht niedrig für 0, hoch für 1. Zwischen zulässigen Bereichen können undefinierte Bereiche liegen. Konkrete Spannungen hängen von der Schaltung ab; die Grafik ist keine Messkurve.",
      "0 bedeutet nicht allgemein kein Strom. Hoch und niedrig sind Bereiche, keine universell festen Spannungen.",
      "Wie heißt eine Informationseinheit mit genau diesen zwei möglichen Werten?",
      "1: Symbole 0 und 1 zuordnen. 2: Bedeutung und Grenze der Vereinfachung.",
      "Texas Instruments: https://www.ti.com/lit/an/szza036c/szza036c.pdf",
    ),
  },
  {
    chapter: "Bits",
    title: "Ein Bit hat zwei mögliche Werte",
    eyebrow: "Der neue Begriff · Bit",
    heading: "Ein Bit. Zwei Möglichkeiten.",
    html: `<div class="split"><div style="text-align:center"><button id="single-bit" class="bit-toggle" aria-label="Bit umschalten" aria-pressed="false">0</button><p class="mini" style="margin-top:14px">Klicken oder mit Leertaste umschalten.</p></div><div><div class="definition">Ein <em>Bit</em> ist eine Informationseinheit mit dem Wert <span class="blue">0</span> oder <span class="orange">1</span>.</div>${frag(1, '<p class="lead">Mit mehreren Bits können wir mehr darstellen.</p>')}</div></div>`,
    bottom: "Wie stellen wir damit mehr als nur zwei Möglichkeiten dar?",
    notes: note(
      "Bit als kleinste binäre Informationseinheit greifbar machen.",
      "Wie viele verschiedene Werte kann dieses einzelne Feld annehmen?",
      "Zwei: 0 und 1.",
      "Das Feld mehrfach umschalten lassen. Das Bit ist ein abstrakter Informationswert und nicht identisch mit einem bestimmten Bauteil. Zwei Bits ermöglichen vier Kombinationen; bei Interesse 00, 01, 10, 11 nennen.",
      "Ein Bit kann nicht allein beliebige Zahlen speichern. „0 oder 1“ bedeutet zwei Möglichkeiten, nicht zwei Bits.",
      "Wir kombinieren acht Bits und vereinbaren eine Regel für Zahlen.",
      "Interaktion: einzelnes Bit. 1: Übergang zu mehreren Bits.",
    ),
  },
  {
    chapter: "Bits als Zahlen",
    title: "Wie wird 00000101 zur Zahl 5?",
    eyebrow: "Bits als Zahlen · gemeinsam ausprobieren",
    heading: "Jede Stelle hat einen Wert",
    lead: "Eine 1 zählt den Stellenwert mit. Eine 0 lässt ihn weg.",
    html: `${bitBoard("explore", 5)}${frag(1, '<p class="mini" style="text-align:center">Von rechts nach links verdoppelt sich der Stellenwert: 1, 2, 4, 8 …</p>')}<button class="reset" data-reset="explore" data-value="5">Zurück zu 5</button>`,
    bottom: "Schaltet eine Stelle um. Was ändert sich an der Zahl?",
    notes: note(
      "Binäre Stellenwerte über unmittelbare Zustandsänderung erklären.",
      "Warum stehen bei der Zahl 5 genau die Stellen 4 und 1 auf 1?",
      "Weil 4 + 1 = 5.",
      "Wir verwenden acht Bits als vorzeichenlose ganze Zahl. Die rechte Stelle zählt 1, dann 2, 4 und so weiter. Nur aktive Stellen werden addiert. Voreinstellung 00000101 ergibt 5. Nach Klicks verändert sich die Summe sofort. Null aktive Stellen ergibt 0, alle Stellen 255.",
      "00000101 ist nicht fünfhunderteins. Andere vereinbarte Formate können dieselben Bits anders interpretieren. Binärarithmetik ist hier nicht das Lernziel.",
      "Jetzt eine neue Zahl selbst darstellen lassen.",
      "Interaktion: acht Stellen umschalten. 1: Verdopplungsregel. „Zurück zu 5“ stellt nur die Bits zurück.",
    ),
  },
  {
    chapter: "Verständnischeck",
    title: "Baut die Zahl 9",
    eyebrow: "Denkpause 02 · Selber bauen",
    heading: "Welche Bits ergeben 9?",
    lead: "Erst vorhersagen. Dann die passenden Stellen einschalten.",
    html: `${bitBoard("challenge", 0)}${answer(1, "00001001 · Die Stellen 8 und 1 sind eingeschaltet.", "8 + 1 = 9. Die anderen Stellen tragen nichts zur Summe bei.")}<button class="reset" data-reset="challenge" data-value="0">Alle Bits auf 0</button>`,
    bottom: "Die Auflösung verändert eure gewählte Bitfolge nicht.",
    notes: note(
      "Stellenwerte auf eine neue Zahl übertragen.",
      "Welche beiden Stellen brauchen wir für 9?",
      "8 und 1; möglicherweise zuerst 4 und 5, obwohl es keine 5er-Stelle gibt.",
      "Teilnehmende vor dem Klicken begründen lassen. Mit den Bits ausprobieren. Die Summe gibt direkt Rückmeldung, die ausgeschriebene Lösung kommt erst mit Weiter. Als Anschluss kann die 3 aus unserer Rechnung mit 2 und 1 dargestellt werden.",
      "Die Anzahl eingeschalteter Bits ist nicht der Zahlenwert. Zwei eingeschaltete Bits können viele verschiedene Zahlen darstellen.",
      "Bits können Zahlen sein. Können sie auch festlegen, was mit Zahlen passieren soll?",
      "Interaktion: Zahl 9 bauen. 1: Lösung zeigen, ohne die Auswahl zu überschreiben.",
    ),
  },
  {
    chapter: "Bits als Befehle",
    title: "Die Bits allein verraten ihre Bedeutung nicht",
    eyebrow: "Der entscheidende Perspektivwechsel",
    heading: "Ist 0010 immer die Zahl 2?",
    html: `<div class="context-bit">0010</div><div class="grid two">${frag(1, '<span class="term blue">Als vorzeichenlose Binärzahl</span><h3>Die Zahl 2</h3>', "card")}${frag(2, '<span class="term">Als Befehlsteil</span><h3>Die Operation „addieren“</h3>', "card")}</div>${frag(2, model)}`,
    bottom:
      "Die Bedeutung ergibt sich aus dem Kontext und den vereinbarten Regeln.",
    notes: note(
      "Zwischen Bitmuster und Interpretation unterscheiden.",
      "Kann man allein an 0010 erkennen, wofür die Bits gerade verwendet werden?",
      "Als Zahl 2; als Befehl vielleicht etwas anderes.",
      "Erst die bekannte Zahlinterpretation zeigen. Danach bewusst die Perspektive wechseln: Unsere erfundene CPU soll dieselben vier Bits an einer bestimmten Stelle einer Anweisung als Addieren deuten. Ob Bits als Anweisung oder Daten behandelt werden, ergibt sich aus ihrer Verwendung im Ablauf; es gibt kein allgemeines sichtbares Etikett an den Bits.",
      "0010 heißt nicht für jede CPU Addieren. Die CPU errät die Bedeutung nicht aus der Bitfolge.",
      "Wir müssen die Regeln dieser CPU also vorher festlegen.",
      "1: Zahleninterpretation. 2: Befehlsinterpretation und Modellhinweis.",
    ),
  },
  {
    chapter: "Bits als Befehle",
    title: "Feste Regeln für die CPU",
    eyebrow: "Ein bewusst erfundenes Modell",
    heading: "Unsere CPU bekommt feste Regeln",
    html: `${model}<div class="grid two dictionary"><div class="card"><code>0001</code><div><h3>Wert übernehmen</h3><p>LOAD · einen Wert in das Register setzen</p></div></div>${frag(1, "<code>0010</code><div><h3>Addieren</h3><p>ADD · einen Wert dazuzählen</p></div>", "card")}${frag(2, "<code>0011</code><div><h3>Ablegen</h3><p>STORE · Registerinhalt im RAM ablegen</p></div>", "card")}${frag(2, "<code>0100</code><div><h3>Weiterspringen</h3><p>JUMP · bei einer anderen Anweisung weitermachen</p></div>", "card")}</div>`,
    bottom:
      "Die Wörter LOAD und ADD sind Lesehilfen für uns. Die CPU erhält Bits.",
    notes: note(
      "Feste Zuordnung von Bitmuster und Operation zeigen.",
      "Wer legt fest, was 0010 als Teil einer Anweisung bedeutet?",
      "Die Konstruktion der CPU beziehungsweise ihre festgelegten Regeln.",
      "Unsere CPU ist ein erfundenes 12-Bit-Modell: 4 Bits für die Operation, 8 Bits für einen Wert oder eine Adresse. Der aktuelle Rechenstand liegt in ihrem Register. LOAD setzt ihn, ADD zählt dazu, STORE schreibt ihn an die angegebene Speicheradresse, JUMP setzt an der angegebenen Anweisungsadresse fort. Es gibt getrennte Daten- und Anweisungsadressen von 0 bis 255. Die übrigen Operationen sind hier nicht definiert. LOAD, ADD und STORE werden praktisch benutzt. Die Detailregeln stehen im README. Bei echten CPUs beschreibt der Befehlssatz solche Regeln.",
      "Die Tabelle wird nicht bei jeder echten Anweisung als Text nachgeschlagen. Sie veranschaulicht feste Regeln, die durch Hardware realisiert werden. ADD ist nicht das, was die CPU als Wort liest.",
      "„Addieren“ allein sagt noch nicht, welcher Wert dazukommen soll.",
      "1: ADD hervorheben. 2: STORE und JUMP als weitere Möglichkeiten. Die englischen Namen nicht abfragen.",
      "Intel: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
    ),
  },
  {
    chapter: "Maschinenanweisung",
    title: "Addieren – aber was?",
    eyebrow: "Zurück zu unserer Rechnung",
    heading: "„Addieren“ reicht noch nicht",
    html: `<div class="instruction"><div class="field operation"><code>0010</code><div class="meaning">Addieren</div></div><div class="field value"><code class="fragment" data-step="1">00000011</code><div class="meaning"><span class="fragment" data-step="1">Wert 3</span><small>Was muss hier stehen?</small></div></div></div>${answer(2, "Addiere 3 zum bisherigen Rechenstand.", "Wir nehmen an: Der Rechenstand ist bereits 5.")}${model}`,
    bottom:
      "Ein Teil bestimmt die Operation. Ein anderer gibt hier den Wert an.",
    notes: note(
      "Die Notwendigkeit eines zusätzlichen Werts entstehen lassen.",
      "Was fehlt der Anweisung, wenn sie nur „addieren“ sagt?",
      "Was addiert werden soll; die Zahl 3.",
      "Wir nehmen jetzt an, dass die CPU schon den Rechenstand 5 hat. Die Anweisung soll 3 dazuzählen. Die vier orangefarbenen Bits bestimmen Addieren; die acht blauen Bits stellen 3 dar, denn 2 + 1 = 3.",
      "Die Trennung ist Teil unseres festgelegten Formats. Nicht jede echte Anweisung besteht genau aus zwei solchen Feldern.",
      "Für den orangefarbenen Teil gibt es einen Fachbegriff.",
      "1: Wert 3 zeigen. 2: Ganze Bedeutung als Satz lesen.",
    ),
  },
  {
    chapter: "Opcode",
    title: "Opcode: Welche Operation?",
    eyebrow: "Der neue Begriff · Opcode",
    heading: "Der Opcode sagt: Was tun?",
    html: `${field()}${frag(1, '<div class="definition" style="font-size:2.5cqw"><em>Opcode</em> = der Teil einer Maschinenanweisung, der die Operation festlegt.</div>')}${frag(2, '<p class="mini"><span class="orange">Operation Code</span> → hier: <span class="mono orange">0010</span> für „addieren“.</p>')}${model}`,
    bottom: "Der Opcode ist der Befehlsteil – nicht die gesamte Anweisung.",
    notes: note(
      "Opcode genau am bekannten Beispiel benennen.",
      "Welcher Teil sagt der CPU, was sie tun soll?",
      "0010, der orangefarbene Teil.",
      "Erst das Feld lokalisieren, danach den Namen Operation Code und seine Kurzform Opcode nennen. Der Opcode legt die Operation fest. Bei echten Architekturen kann die Operationscodierung auf mehrere Felder verteilt sein. Das einfache 4-Bit-Feld ist eine didaktische Wahl.",
      "0010 ist nur in unserem Modell ADD. Ein Opcode ist nicht automatisch die gesamte Maschinenanweisung und muss nicht vier Bits lang sein.",
      "Auch das, womit die Operation arbeitet, hat einen Namen.",
      "1: Definition. 2: Herkunft des Namens.",
      "Intel, Formate und Referenz: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
    ),
  },
  {
    chapter: "Opcode & Operand",
    title: "Operand: Womit wird gearbeitet?",
    eyebrow: "Der ergänzende Begriff · Operand",
    heading: "Der Operand sagt: Womit?",
    html: `${field()}${frag(1, '<div class="definition" style="font-size:2.5cqw">Ein <span class="blue">Operand</span> ist ein Wert oder eine Datenstelle, mit dem oder der eine Operation arbeitet.</div>')}${frag(2, '<p class="mini">Hier ist der Operand der direkt angegebene Wert <span class="blue">3</span>. Andere Anweisungen können auf Datenstellen verweisen.</p>')}${model}`,
    bottom: "Opcode: addieren. Operand in diesem Feld: 3.",
    notes: note(
      "Operand getrennt vom Opcode einführen.",
      "Was steht in unserem blauen Feld?",
      "Die Zahl 3 als 00000011.",
      "Hier ist 3 ein direkt in der Anweisung angegebener Wert, ein unmittelbarer Operand. Der bestehende Rechenstand ist bei unserer CPU stillschweigend als weiterer Operand und als Ziel festgelegt. In anderen Formaten können Datenstellen angegeben werden. An die gerade eingeführten Register und Adressen erinnern.",
      "Nicht jede Anweisung hat genau einen expliziten Operanden. Ein Operandenfeld enthält nicht immer den Wert selbst; es kann ihn auch über eine Datenstelle bezeichnen.",
      "Jetzt prüfen wir, ob die beiden Rollen wirklich getrennt verstanden wurden.",
      "1: Begriff und Definition. 2: Konkretisierung für diesen Wert.",
      "Intel, Instruction Set Reference: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html",
    ),
  },
  {
    chapter: "Verständnischeck",
    title: "Was muss sich für plus 5 ändern?",
    eyebrow: "Denkpause 03 · Einen Befehl verändern",
    heading: "Jetzt soll die CPU 5 dazuzählen",
    lead: "Bisher: addiere 3. Welcher Teil muss sich ändern?",
    html: `${field()}<div class="grid two"><button class="choice" data-choice><b>A</b>Der orange Befehlsteil</button><button class="choice" data-choice><b>B</b>Das blaue Wertefeld</button></div>${answer(1, "B · Addieren bleibt Addieren. Der Wert ändert sich.", "0010 | 00000101 → addiere 5. Der Opcode bleibt gleich.")}${model}`,
    bottom: "Erst das „Was“, dann das „Womit“ auseinanderhalten.",
    notes: note(
      "Opcode und Operand durch eine Änderung unterscheiden.",
      "Wie ändern wir „addiere 3“ zu „addiere 5“?",
      "Das Wertefeld wird 00000101; der Opcode 0010 bleibt.",
      "Erst die Rollen benennen lassen. Danach die neue Codierung zeigen. Bei festgelegtem alten Rechenstand 5 wäre das neue Ergebnis 10. Für die nächste Folie kehren wir ausdrücklich zu plus 3 zurück.",
      "Die Ziffer 5 darf nicht einfach als Zeichen im Bitfeld stehen. Die Operation ändert sich nicht dadurch, dass ein anderer Wert verwendet wird.",
      "Wir haben den Aufbau verstanden. Zurück zu 5 + 3: Was verändert die Ausführung?",
      "Auswahl markiert nur eine Vermutung. 1: Lösung und neue Codierung.",
    ),
  },
  {
    chapter: "Zusammensetzen",
    title: "Was die Anweisung verändert",
    eyebrow: "Unser Beispiel wird vollständig",
    heading: "Aus 5 wird 8",
    html: `${model}<div class="instruction"><div class="field operation"><code style="font-size:3cqw">0010</code><div class="meaning">Addieren</div></div><div class="field value"><code style="font-size:3cqw">00000011</code><div class="meaning">Wert 3</div></div></div><div class="state"><div class="card"><small>Rechenstand vorher</small><strong class="big blue">5</strong></div><span class="arrow fragment" data-step="1">→</span>${frag(1, '<small>Rechenstand danach</small><strong class="big mint">8</strong>', "card")}</div>`,
    bottom:
      "Die Anweisung beschreibt eine Operation. Ihre Ausführung verändert einen Zustand.",
    notes: note(
      "Bits, Bedeutung und sichtbare Zustandsänderung zusammenführen.",
      "Welcher Rechenstand steht nach dieser Anweisung da?",
      "8, weil zu 5 der Wert 3 addiert wird.",
      "Wir sind wieder bei plus 3. Rechenstand ist der vorhandene Zahlenwert der CPU; den Fachbegriff Register führen wir erst später ein. Das hier ist eine einzelne Zustandsänderung, noch keine Fetch-Decode-Execute-Simulation.",
      "Die Anweisung ist nicht selbst das Ergebnis. Ihr Bitmuster enthält hier 3, nicht bereits 8.",
      "Können wir jetzt einen typischen Irrtum über das Wort ADD auflösen?",
      "1: Zustand 8 einblenden, vorher von der Gruppe berechnen lassen.",
    ),
  },
  {
    chapter: "Verständnischeck",
    title: "Liest die CPU das Wort ADD?",
    eyebrow: "Zum Schluss · Einen Irrtum aufdecken",
    heading: "„Die CPU liest das Wort ADD.“",
    lead: "Stimmt das für unsere Maschinenanweisung?",
    html: `<div class="grid two"><button class="choice" data-choice><b>A</b>Ja, ADD ist der Befehl.</button><button class="choice" data-choice><b>B</b>Nein, ADD ist unsere Lesehilfe.</button></div>${answer(1, "B · Die CPU erhält das codierte Bitmuster.", "In unserem Beispiel steht 0010 für die Operation. ADD ist der menschenlesbare Name dafür.")}${model}`,
    bottom:
      "Warum könnten solche Lesehilfen beim Programmieren praktisch sein?",
    notes: note(
      "Maschinenanweisung und menschenlesbaren Namen unterscheiden.",
      "Wird das Wort ADD als Text anstelle des Opcodes ausgeführt?",
      "Nein; die CPU bekommt Bits. ADD ist für Menschen leichter lesbar.",
      "Präzise bleiben: Eine CPU kann natürlich über Programme Textdaten mit den Zeichen ADD verarbeiten. Die Aussage bezieht sich auf die Ausführung der Maschinenanweisung. Die Zeichen ADD sind nicht unser vierstelliger Opcode.",
      "Nicht pauschal behaupten, eine CPU könne niemals die Zeichen ADD als Daten erhalten.",
      "Das ist die Brücke zum nächsten Abschnitt: menschenlesbare Maschinenbefehle und ihr Übersetzer.",
      "1: Antwort einblenden. Anschlussfrage offen sammeln.",
    ),
  },
  {
    chapter: "Zwischenstand",
    title: "Unser Weg bis zum Opcode",
    eyebrow: "Zwischenstand · Der erste Teil steht",
    heading: "Die Bits haben jetzt eine Rolle",
    html: `<div class="summary-list"><div class="card"><span class="term">01 / Programm</span><h3>Welche Schritte?</h3><p>Eine ausführbare Folge von Anweisungen.</p></div><div class="card"><span class="term">02 / CPU</span><h3>Wer führt aus?</h3><p>Der Prozessor führt Maschinenanweisungen aus.</p></div><div class="card"><span class="term">03 / Opcode</span><h3>Was soll passieren?</h3><p>Der Befehlsteil bestimmt die Operation.</p></div></div><div class="flow"><div class="node">Idee<br><span class="mono blue">5 + 3</span></div><span class="arrow">→</span><div class="node unknown">?</div><span class="arrow">→</span><div class="node accent mono">0010 | 00000011</div><span class="arrow">→</span><div class="node">CPU<br><span class="mint">5 → 8</span></div></div>${frag(1, '<div class="next-topic">Als Nächstes: <em>Wie schreiben Menschen solche Befehle lesbar?</em></div>')}`,
    bottom:
      "Die Übersetzung von unserer Idee zu Maschinenanweisungen bleibt die nächste offene Frage.",
    notes: note(
      "Erreichtes sichern und sauber am gewünschten Abschnittsende stoppen.",
      "Welche Teile der Kette könnt ihr jetzt jemand anderem erklären?",
      "Programm, CPU, Bits, Bedeutung durch Regeln, Opcode und Operand.",
      "Die Kette ist eine Übersicht, kein vollständiges Ablaufdiagramm. Für die gezeigte einzelne ADD-Anweisung setzen wir Rechenstand 5 voraus. Die Lücke enthält später Programmiersprachen und Übersetzung; das Starten und die Rolle des Betriebssystems folgen ebenfalls erst später. Es wurde noch kein kompletter Weg von Eingabe bis Ergebnis behauptet.",
      "Nicht so zusammenfassen, als würde eine CPU die menschliche Idee direkt erhalten. Speicherrollen und Kontext bleiben wichtig.",
      "Nächster Abschnitt: Fetch–Decode–Execute, Register und der Weg zu Assembly/Assembler, je nach Fortsetzung des Storyboards.",
      "1: Offene Anschlussfrage. Am Ende bleibt „Weiter“ deaktiviert.",
    ),
  },
];
